spring:
  config:
    activate:
      on-profile: oracle
  datasource:
    driver-class-name: ${COST_LITE_DB_DRIVER:oracle.jdbc.OracleDriver}
    url: ${COST_LITE_DB_URL}
    username: ${COST_LITE_DB_USERNAME}
    password: ${COST_LITE_DB_PASSWORD}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
