spring:
  config:
    activate:
      on-profile: oracle
  datasource:
    driver-class-name: ${COST_LITE_DB_DRIVER:oracle.jdbc.OracleDriver}
    url: ${COST_LITE_DB_URL}
    username: ${COST_LITE_DB_USERNAME}
    password: ${COST_LITE_DB_PASSWORD}
    hikari:
      minimum-idle: ${COST_LITE_DB_MIN_IDLE:1}
      maximum-pool-size: ${COST_LITE_DB_MAX_POOL_SIZE:10}
      connection-timeout: ${COST_LITE_DB_CONNECTION_TIMEOUT:5000}
      validation-timeout: 3000
      initialization-fail-timeout: -1

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
