-- Cost Lite Oracle schema baseline
-- Generated from the frozen MySQL entity baseline; no DROP statements are used.
-- Oracle 12c+ / 19c / 23ai. Empty strings are represented by Oracle as NULL.

-- =========================================================
-- cost_scene
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_scene (
  scene_id                  NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_code                VARCHAR2(64 CHAR)     not null,
  scene_name                VARCHAR2(128 CHAR)    not null,
  business_domain           VARCHAR2(64 CHAR)     not null,
  org_code                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  scene_type                VARCHAR2(32 CHAR)     default 'CONTRACT',
  active_version_id         NUMBER(19)          default null,
  default_object_dimension  VARCHAR2(64 CHAR)     DEFAULT NULL,
  status                    CHAR(1 CHAR)         DEFAULT '0' NOT NULL,
  remark                    VARCHAR2(500 CHAR)    default null,
  create_by                 VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time               TIMESTAMP(6)        default SYSTIMESTAMP,
  update_by                 VARCHAR2(64 CHAR)     DEFAULT NULL,
  update_time               TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_scene_code unique (scene_code),
  constraint pk_cost_scene primary key (scene_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_fee_item
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_fee_item (
  fee_id                    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id                  NUMBER(19)          not null,
  fee_code                  VARCHAR2(64 CHAR)     not null,
  fee_name                  VARCHAR2(128 CHAR)    not null,
  fee_category              VARCHAR2(64 CHAR)     DEFAULT NULL,
  unit_code                 VARCHAR2(32 CHAR)     DEFAULT NULL,
  factor_summary            VARCHAR2(255 CHAR)    DEFAULT NULL,
  scope_description         VARCHAR2(255 CHAR)    DEFAULT NULL,
  object_dimension          VARCHAR2(64 CHAR)     DEFAULT NULL,
  sort_no                   NUMBER(10)             DEFAULT 0 NOT NULL,
  status                    CHAR(1 CHAR)         DEFAULT '0' NOT NULL,
  remark                    VARCHAR2(500 CHAR)    default null,
  create_by                 VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time               TIMESTAMP(6)        default SYSTIMESTAMP,
  update_by                 VARCHAR2(64 CHAR)     DEFAULT NULL,
  update_time               TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_fee_scene_code unique (scene_id, fee_code),
  constraint fk_cost_fee_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint pk_cost_fee_item primary key (fee_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_variable_group
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_variable_group (
  group_id                  NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id                  NUMBER(19)          not null,
  group_code                VARCHAR2(64 CHAR)     not null,
  group_name                VARCHAR2(128 CHAR)    not null,
  sort_no                   NUMBER(10)             DEFAULT 0 NOT NULL,
  status                    CHAR(1 CHAR)         DEFAULT '0' NOT NULL,
  remark                    VARCHAR2(500 CHAR)    default null,
  create_by                 VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time               TIMESTAMP(6)        default SYSTIMESTAMP,
  update_by                 VARCHAR2(64 CHAR)     DEFAULT NULL,
  update_time               TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_var_group_scene_code unique (scene_id, group_code),
  constraint fk_cost_var_group_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint pk_cost_variable_group primary key (group_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_variable
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_variable (
  variable_id               NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id                  NUMBER(19)          not null,
  group_id                  NUMBER(19)          default null,
  variable_code             VARCHAR2(64 CHAR)     not null,
  variable_name             VARCHAR2(128 CHAR)    not null,
  variable_type             VARCHAR2(32 CHAR)     not null,
  source_type               VARCHAR2(32 CHAR)     not null,
  source_system             VARCHAR2(64 CHAR)     DEFAULT NULL,
  dict_type                 VARCHAR2(64 CHAR)     DEFAULT NULL,
  remote_api                VARCHAR2(255 CHAR)    DEFAULT NULL,
  request_method            VARCHAR2(16 CHAR)     default 'GET',
  content_type              VARCHAR2(128 CHAR)    default 'application/json',
  query_config_json         CLOB            default null,
  request_headers_json      CLOB            default null,
  body_template_json        CLOB            default null,
  auth_type                 VARCHAR2(32 CHAR)     default 'NONE',
  auth_config_json          CLOB            default null,
  data_path                 VARCHAR2(255 CHAR)    DEFAULT NULL,
  response_config_json      CLOB            default null,
  mapping_config_json       CLOB            default null,
  page_config_json          CLOB            default null,
  sync_mode                 VARCHAR2(32 CHAR)     default 'REALTIME',
  cache_policy              VARCHAR2(32 CHAR)     default 'MANUAL_REFRESH',
  fallback_policy           VARCHAR2(32 CHAR)     default 'FAIL_FAST',
  adapter_type              VARCHAR2(32 CHAR)     default 'STANDARD',
  adapter_config_json       CLOB            default null,
  formula_expr              VARCHAR2(2000 CHAR)   default null,
  formula_code              VARCHAR2(64 CHAR)     DEFAULT NULL,
  data_type                 VARCHAR2(32 CHAR)     default 'STRING',
  default_value             VARCHAR2(255 CHAR)    DEFAULT NULL,
  precision_scale           NUMBER(10)             default 2,
  status                    CHAR(1 CHAR)         DEFAULT '0' NOT NULL,
  sort_no                   NUMBER(10)             DEFAULT 0 NOT NULL,
  remark                    VARCHAR2(500 CHAR)    default null,
  create_by                 VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time               TIMESTAMP(6)        default SYSTIMESTAMP,
  update_by                 VARCHAR2(64 CHAR)     DEFAULT NULL,
  update_time               TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_variable_scene_code unique (scene_id, variable_code),
  constraint fk_cost_variable_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint fk_cost_variable_group foreign key (group_id) references cost_variable_group (group_id),
  constraint pk_cost_variable primary key (variable_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_fee_variable_rel
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_fee_variable_rel (
  rel_id                    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id                  NUMBER(19)          not null,
  fee_id                    NUMBER(19)          not null,
  variable_id               NUMBER(19)          not null,
  relation_type             VARCHAR2(32 CHAR)     DEFAULT 'OPTIONAL' NOT NULL,
  source_type               VARCHAR2(32 CHAR)     DEFAULT 'RULE_DERIVED' NOT NULL,
  source_rule_id            NUMBER(19)          default null,
  source_code               VARCHAR2(128 CHAR)    DEFAULT NULL NOT NULL,
  sort_no                   NUMBER(10)             DEFAULT 0 NOT NULL,
  remark                    VARCHAR2(500 CHAR)    default null,
  create_by                 VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time               TIMESTAMP(6)        default SYSTIMESTAMP,
  update_by                 VARCHAR2(64 CHAR)     DEFAULT NULL,
  update_time               TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_fee_var_rel unique (fee_id, variable_id, relation_type, source_type, source_code),
  constraint fk_cost_fee_var_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint fk_cost_fee_var_fee foreign key (fee_id) references cost_fee_item (fee_id),
  constraint fk_cost_fee_var_variable foreign key (variable_id) references cost_variable (variable_id),
  constraint pk_cost_fee_variable_rel primary key (rel_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_rule
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_rule (
  rule_id                    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id                   NUMBER(19)          not null,
  fee_id                     NUMBER(19)          not null,
  rule_code                  VARCHAR2(64 CHAR)     not null,
  rule_name                  VARCHAR2(128 CHAR)    DEFAULT NULL,
  rule_type                  VARCHAR2(32 CHAR)     not null,
  condition_logic            VARCHAR2(16 CHAR)     DEFAULT 'AND' NOT NULL,
  priority                   NUMBER(10)             DEFAULT 0 NOT NULL,
  quantity_variable_code     VARCHAR2(64 CHAR)     DEFAULT NULL,
  pricing_mode               VARCHAR2(32 CHAR)     DEFAULT 'TYPED' NOT NULL,
  pricing_json               CLOB            default null,
  amount_formula             VARCHAR2(2000 CHAR)   default null,
  amount_formula_code        VARCHAR2(64 CHAR)     DEFAULT NULL,
  note_template              VARCHAR2(500 CHAR)    DEFAULT NULL,
  status                     CHAR(1 CHAR)         DEFAULT '0' NOT NULL,
  sort_no                    NUMBER(10)             DEFAULT 0 NOT NULL,
  remark                     VARCHAR2(500 CHAR)    default null,
  create_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  update_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  update_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_rule_scene_code unique (scene_id, rule_code),
  constraint fk_cost_rule_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint fk_cost_rule_fee foreign key (fee_id) references cost_fee_item (fee_id),
  constraint pk_cost_rule primary key (rule_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_rule_condition
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_rule_condition (
  condition_id               NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id                   NUMBER(19)          not null,
  rule_id                    NUMBER(19)          not null,
  group_no                   NUMBER(10)             DEFAULT 1 NOT NULL,
  sort_no                    NUMBER(10)             DEFAULT 0 NOT NULL,
  variable_code              VARCHAR2(64 CHAR)     not null,
  display_name               VARCHAR2(128 CHAR)    DEFAULT NULL,
  operator_code              VARCHAR2(32 CHAR)     not null,
  compare_value              VARCHAR2(1000 CHAR)   DEFAULT NULL,
  status                     CHAR(1 CHAR)         DEFAULT '0' NOT NULL,
  remark                     VARCHAR2(500 CHAR)    default null,
  create_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  update_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  update_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint fk_cost_rule_condition_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint fk_cost_rule_condition_rule foreign key (rule_id) references cost_rule (rule_id),
  constraint pk_cost_rule_condition primary key (condition_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_rule_tier
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_rule_tier (
  tier_id                    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id                   NUMBER(19)          not null,
  rule_id                    NUMBER(19)          not null,
  start_value                NUMBER(18,4)   default null,
  end_value                  NUMBER(18,4)   default null,
  rate_value                 NUMBER(18,6)   not null,
  interval_mode              VARCHAR2(32 CHAR)     DEFAULT 'LEFT_CLOSED_RIGHT_OPEN' NOT NULL,
  tier_no                    NUMBER(10)             DEFAULT 1 NOT NULL,
  status                     CHAR(1 CHAR)         DEFAULT '0' NOT NULL,
  remark                     VARCHAR2(500 CHAR)    default null,
  create_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  update_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  update_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint fk_cost_rule_tier_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint fk_cost_rule_tier_rule foreign key (rule_id) references cost_rule (rule_id),
  constraint pk_cost_rule_tier primary key (tier_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_formula
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_formula (
    formula_id             NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    scene_id               NUMBER(19)          not null,
    formula_code           VARCHAR2(64 CHAR)     not null,
    formula_name           VARCHAR2(128 CHAR)    not null,
    formula_desc           VARCHAR2(500 CHAR)    DEFAULT NULL,
    business_formula       VARCHAR2(1000 CHAR)   DEFAULT NULL,
    formula_expr           VARCHAR2(2000 CHAR)   not null,
    asset_type             VARCHAR2(32 CHAR)     default 'FORMULA',
    workbench_mode         VARCHAR2(32 CHAR)     default 'GUIDED',
    workbench_pattern      VARCHAR2(32 CHAR)     default 'IF_ELSE',
    template_code          VARCHAR2(64 CHAR)     DEFAULT NULL,
    workbench_config_json  CLOB            default null,
    namespace_scope        VARCHAR2(128 CHAR)    default 'V,C,I,F,T',
    return_type            VARCHAR2(32 CHAR)     default 'NUMBER',
    test_case_json         CLOB            default null,
    sample_result_json     CLOB            default null,
    last_test_time         TIMESTAMP(6)        default null,
    status                 CHAR(1 CHAR)         default '0',
    sort_no                NUMBER(10)             default 10,
    remark                 VARCHAR2(500 CHAR)    DEFAULT NULL,
    create_by              VARCHAR2(64 CHAR)     DEFAULT NULL,
    create_time            TIMESTAMP(6)        default SYSTIMESTAMP,
    update_by              VARCHAR2(64 CHAR)     DEFAULT NULL,
    update_time            TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_formula_scene_code unique (scene_id, formula_code),
  constraint pk_cost_formula primary key (formula_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_formula_version
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_formula_version (
    version_id             NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    formula_id             NUMBER(19)          not null,
    scene_id               NUMBER(19)          not null,
    formula_code           VARCHAR2(64 CHAR)     not null,
    formula_name           VARCHAR2(128 CHAR)    not null,
    asset_type             VARCHAR2(32 CHAR)     default 'FORMULA',
    version_no             NUMBER(10)             not null,
    change_type            VARCHAR2(32 CHAR)     default 'UPDATE',
    business_formula       VARCHAR2(1000 CHAR)   DEFAULT NULL,
    formula_expr           VARCHAR2(2000 CHAR)   DEFAULT NULL,
    workbench_mode         VARCHAR2(32 CHAR)     default 'GUIDED',
    workbench_pattern      VARCHAR2(32 CHAR)     default 'IF_ELSE',
    template_code          VARCHAR2(64 CHAR)     DEFAULT NULL,
    workbench_config_json  CLOB            default null,
    snapshot_json          CLOB            default null,
    create_by              VARCHAR2(64 CHAR)     DEFAULT NULL,
    create_time            TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_formula_version_no unique (formula_id, version_no),
  constraint pk_cost_formula_version primary key (version_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_publish_version
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_publish_version (
  version_id                 NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id                   NUMBER(19)          not null,
  version_no                 VARCHAR2(64 CHAR)     not null,
  version_status             VARCHAR2(32 CHAR)     DEFAULT 'PUBLISHED' NOT NULL,
  publish_desc               VARCHAR2(1000 CHAR)   DEFAULT NULL,
  validation_result_json     CLOB            default null,
  snapshot_hash              VARCHAR2(128 CHAR)    DEFAULT NULL,
  published_by               VARCHAR2(64 CHAR)     DEFAULT NULL,
  published_time             TIMESTAMP(6)        default null,
  activated_by               VARCHAR2(64 CHAR)     DEFAULT NULL,
  activated_time             TIMESTAMP(6)        default null,
  rollback_by                VARCHAR2(64 CHAR)     DEFAULT NULL,
  rollback_time              TIMESTAMP(6)        default null,
  create_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  update_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  update_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_publish_scene_ver unique (scene_id, version_no),
  constraint fk_cost_publish_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint pk_cost_publish_version primary key (version_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_publish_snapshot
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_publish_snapshot (
  snapshot_id                NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  version_id                 NUMBER(19)          not null,
  snapshot_type              VARCHAR2(32 CHAR)     not null,
  object_code                VARCHAR2(64 CHAR)     not null,
  object_name                VARCHAR2(128 CHAR)    DEFAULT NULL,
  snapshot_json              CLOB            not null,
  sort_no                    NUMBER(10)             DEFAULT 0 NOT NULL,
  create_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint fk_cost_snapshot_version foreign key (version_id) references cost_publish_version (version_id),
  constraint pk_cost_publish_snapshot primary key (snapshot_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_simulation_record
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_simulation_record (
  simulation_id              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id                   NUMBER(19)          not null,
  version_id                 NUMBER(19)          default null,
  bill_month                 VARCHAR2(16 CHAR)     DEFAULT NULL NOT NULL,
  simulation_no              VARCHAR2(64 CHAR)     not null,
  input_json                 CLOB            not null,
  variable_json              CLOB            default null,
  explain_json               CLOB            default null,
  result_json                CLOB            default null,
  status                     VARCHAR2(32 CHAR)     DEFAULT 'SUCCESS' NOT NULL,
  error_message              VARCHAR2(1000 CHAR)   DEFAULT NULL,
  create_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_simulation_no unique (simulation_no),
  constraint fk_cost_simulation_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint fk_cost_simulation_version foreign key (version_id) references cost_publish_version (version_id),
  constraint pk_cost_simulation_record primary key (simulation_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_audit_log
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_audit_log (
  audit_id                   NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id                   NUMBER(19)          default null,
  object_type                VARCHAR2(32 CHAR)     not null,
  object_code                VARCHAR2(64 CHAR)     DEFAULT NULL,
  action_type                VARCHAR2(32 CHAR)     not null,
  action_summary             VARCHAR2(500 CHAR)    DEFAULT NULL,
  before_json                CLOB            default null,
  after_json                 CLOB            default null,
  operator_code              VARCHAR2(64 CHAR)     DEFAULT NULL,
  operator_name              VARCHAR2(128 CHAR)    DEFAULT NULL,
  operate_time               TIMESTAMP(6)        default SYSTIMESTAMP,
  request_no                 VARCHAR2(64 CHAR)     DEFAULT NULL,
  constraint pk_cost_audit_log primary key (audit_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_bill_period
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_bill_period (
  period_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id NUMBER(19) not null,
  bill_month VARCHAR2(7 CHAR) not null,
  period_status VARCHAR2(32 CHAR) DEFAULT 'NOT_STARTED' NOT NULL,
  active_version_id NUMBER(19) default null,
  result_count NUMBER(19) DEFAULT 0 NOT NULL,
  amount_total NUMBER(18,2) DEFAULT 0.00 NOT NULL,
  last_task_id NUMBER(19) default null,
  last_task_no VARCHAR2(64 CHAR) DEFAULT NULL,
  sealed_by VARCHAR2(64 CHAR) DEFAULT NULL,
  sealed_time TIMESTAMP(6) default null,
  create_by VARCHAR2(64 CHAR) DEFAULT NULL,
  create_time TIMESTAMP(6) default SYSTIMESTAMP,
  update_by VARCHAR2(64 CHAR) DEFAULT NULL,
  update_time TIMESTAMP(6) default SYSTIMESTAMP,
  remark VARCHAR2(500 CHAR) DEFAULT NULL,
  constraint uk_cost_bill_period_scene_month unique (scene_id, bill_month),
  constraint pk_cost_bill_period primary key (period_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_recalc_order
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_recalc_order (
  recalc_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id NUMBER(19) not null,
  bill_month VARCHAR2(7 CHAR) not null,
  version_id NUMBER(19) not null,
  period_id NUMBER(19) default null,
  baseline_task_id NUMBER(19) default null,
  baseline_task_no VARCHAR2(64 CHAR) DEFAULT NULL,
  target_task_id NUMBER(19) default null,
  target_task_no VARCHAR2(64 CHAR) DEFAULT NULL,
  recalc_status VARCHAR2(32 CHAR) DEFAULT 'PENDING_APPROVAL' NOT NULL,
  apply_reason VARCHAR2(500 CHAR) DEFAULT NULL,
  approve_opinion VARCHAR2(500 CHAR) DEFAULT NULL,
  diff_summary_json CLOB default null,
  diff_amount NUMBER(18,2) DEFAULT 0.00 NOT NULL,
  request_no VARCHAR2(64 CHAR) DEFAULT NULL,
  approve_by VARCHAR2(64 CHAR) DEFAULT NULL,
  approve_time TIMESTAMP(6) default null,
  execute_by VARCHAR2(64 CHAR) DEFAULT NULL,
  execute_time TIMESTAMP(6) default null,
  finish_time TIMESTAMP(6) default null,
  create_by VARCHAR2(64 CHAR) DEFAULT NULL,
  create_time TIMESTAMP(6) default SYSTIMESTAMP,
  update_by VARCHAR2(64 CHAR) DEFAULT NULL,
  update_time TIMESTAMP(6) default SYSTIMESTAMP,
  remark VARCHAR2(500 CHAR) DEFAULT NULL,
  constraint pk_cost_recalc_order primary key (recalc_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_alarm_record
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_alarm_record (
  alarm_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id NUMBER(19) default null,
  version_id NUMBER(19) default null,
  task_id NUMBER(19) default null,
  detail_id NUMBER(19) default null,
  bill_month VARCHAR2(7 CHAR) DEFAULT NULL,
  alarm_type VARCHAR2(32 CHAR) not null,
  alarm_level VARCHAR2(32 CHAR) DEFAULT 'WARN' NOT NULL,
  alarm_status VARCHAR2(32 CHAR) DEFAULT 'OPEN' NOT NULL,
  source_key VARCHAR2(128 CHAR) DEFAULT NULL,
  alarm_title VARCHAR2(200 CHAR) DEFAULT NULL,
  alarm_content VARCHAR2(1000 CHAR) DEFAULT NULL,
  trigger_time TIMESTAMP(6) default SYSTIMESTAMP,
  first_trigger_time TIMESTAMP(6) null,
  latest_trigger_time TIMESTAMP(6) null,
  occurrence_count NUMBER(10) DEFAULT 1 NOT NULL,
  ack_by VARCHAR2(64 CHAR) DEFAULT NULL,
  ack_time TIMESTAMP(6) default null,
  resolve_by VARCHAR2(64 CHAR) DEFAULT NULL,
  resolve_time TIMESTAMP(6) default null,
  create_by VARCHAR2(64 CHAR) DEFAULT NULL,
  create_time TIMESTAMP(6) default SYSTIMESTAMP,
  update_by VARCHAR2(64 CHAR) DEFAULT NULL,
  update_time TIMESTAMP(6) default SYSTIMESTAMP,
  remark VARCHAR2(500 CHAR) DEFAULT NULL,
  constraint pk_cost_alarm_record primary key (alarm_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_access_profile
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_access_profile (
    profile_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    scene_id NUMBER(19) not null,
    fee_id NUMBER(19) null,
    fee_scope_type VARCHAR2(16 CHAR) DEFAULT 'ALL' NOT NULL,
    fee_ids_json CLOB null,
    version_id NUMBER(19) null,
    profile_code VARCHAR2(64 CHAR) not null,
    profile_name VARCHAR2(128 CHAR) not null,
    source_type VARCHAR2(32 CHAR) DEFAULT 'RAW_JSON' NOT NULL,
    task_type VARCHAR2(32 CHAR) DEFAULT 'FORMAL_BATCH' NOT NULL,
    request_method VARCHAR2(16 CHAR) DEFAULT 'GET' NOT NULL,
    endpoint_url VARCHAR2(255 CHAR) null,
    auth_type VARCHAR2(32 CHAR) DEFAULT 'NONE' NOT NULL,
    auth_config_json CLOB null,
    fetch_config_json CLOB null,
    mapping_json CLOB null,
    sample_payload_json CLOB null,
    sample_input_json CLOB null,
    status CHAR(1 CHAR) DEFAULT '0' NOT NULL,
    sort_no NUMBER(10) DEFAULT 0,
    create_by VARCHAR2(64 CHAR) null,
    create_time TIMESTAMP(6) null,
    update_by VARCHAR2(64 CHAR) null,
    update_time TIMESTAMP(6) null,
    remark VARCHAR2(500 CHAR) null,
  constraint uk_cost_access_profile_scene_code unique (scene_id, profile_code),
  constraint pk_cost_access_profile primary key (profile_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_calc_input_batch
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_calc_input_batch (
  batch_id                   NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  batch_no                   VARCHAR2(64 CHAR)     not null,
  scene_id                   NUMBER(19)          not null,
  version_id                 NUMBER(19)          default null,
  bill_month                 VARCHAR2(16 CHAR)     DEFAULT NULL NOT NULL,
  source_type                VARCHAR2(32 CHAR)     DEFAULT 'JSON_IMPORT' NOT NULL,
  batch_status               VARCHAR2(32 CHAR)     DEFAULT 'READY' NOT NULL,
  total_count                NUMBER(10)             DEFAULT 0 NOT NULL,
  valid_count                NUMBER(10)             DEFAULT 0 NOT NULL,
  error_count                NUMBER(10)             DEFAULT 0 NOT NULL,
  remark                     VARCHAR2(500 CHAR)    default null,
  error_message              VARCHAR2(1000 CHAR)   DEFAULT NULL,
  access_profile_id          NUMBER(19)          null,
  checkpoint_json            CLOB        null,
  create_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  update_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  update_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_calc_input_batch_no unique (batch_no),
  constraint fk_cost_calc_input_batch_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint fk_cost_calc_input_batch_version foreign key (version_id) references cost_publish_version (version_id),
  constraint pk_cost_calc_input_batch primary key (batch_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_calc_input_batch_item
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_calc_input_batch_item (
  item_id                    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  batch_id                   NUMBER(19)          not null,
  batch_no                   VARCHAR2(64 CHAR)     not null,
  item_no                    NUMBER(10)             not null,
  biz_no                     VARCHAR2(128 CHAR)    not null,
  item_status                VARCHAR2(32 CHAR)     DEFAULT 'READY' NOT NULL,
  input_json                 CLOB            not null,
  error_message              VARCHAR2(1000 CHAR)   DEFAULT NULL,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  update_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_calc_input_batch_item unique (batch_id, biz_no),
  constraint fk_cost_calc_input_batch_item_batch foreign key (batch_id) references cost_calc_input_batch (batch_id),
  constraint pk_cost_calc_input_batch_item primary key (item_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_calc_task
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_calc_task (
  task_id                    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  task_no                    VARCHAR2(64 CHAR)     not null,
  scene_id                   NUMBER(19)          not null,
  version_id                 NUMBER(19)          not null,
  task_type                  VARCHAR2(32 CHAR)     not null,
  bill_month                 VARCHAR2(16 CHAR)     DEFAULT NULL,
  source_count               NUMBER(10)             DEFAULT 0 NOT NULL,
  success_count              NUMBER(10)             DEFAULT 0 NOT NULL,
  fail_count                 NUMBER(10)             DEFAULT 0 NOT NULL,
  task_status                VARCHAR2(32 CHAR)     DEFAULT 'INIT' NOT NULL,
  progress_percent           NUMBER(5,2)    DEFAULT 0 NOT NULL,
  started_time               TIMESTAMP(6)        default null,
  finished_time              TIMESTAMP(6)        default null,
  duration_ms                NUMBER(19)          default 0,
  request_no                 VARCHAR2(64 CHAR)     DEFAULT NULL,
  request_no_key             GENERATED ALWAYS AS (CAST(request_no AS VARCHAR2(64 CHAR))) VIRTUAL,
  execute_node               VARCHAR2(128 CHAR)    DEFAULT NULL,
  input_source_type          VARCHAR2(32 CHAR)     DEFAULT 'INLINE_JSON' NOT NULL,
  source_batch_no            VARCHAR2(64 CHAR)     DEFAULT NULL,
  error_message              VARCHAR2(1000 CHAR)   DEFAULT NULL,
  remark                     VARCHAR2(500 CHAR)    default null,
  create_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  update_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  update_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_calc_task_no unique (task_no),
  constraint uk_cost_calc_task_request_no unique (scene_id, version_id, bill_month, request_no_key),
  constraint fk_cost_calc_task_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint fk_cost_calc_task_version foreign key (version_id) references cost_publish_version (version_id),
  constraint pk_cost_calc_task primary key (task_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_calc_task_detail
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_calc_task_detail (
  detail_id                  NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  task_id                    NUMBER(19)          not null,
  task_no                    VARCHAR2(64 CHAR)     not null,
  biz_no                     VARCHAR2(128 CHAR)    not null,
  partition_no               NUMBER(10)             DEFAULT 1 NOT NULL,
  detail_status              VARCHAR2(32 CHAR)     DEFAULT 'INIT' NOT NULL,
  retry_count                NUMBER(10)             DEFAULT 0 NOT NULL,
  input_json                 CLOB            not null,
  result_summary             VARCHAR2(1000 CHAR)   DEFAULT NULL,
  error_message              VARCHAR2(1000 CHAR)   DEFAULT NULL,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  update_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_calc_task_detail unique (task_id, biz_no),
  constraint fk_cost_calc_task_detail_task foreign key (task_id) references cost_calc_task (task_id),
  constraint pk_cost_calc_task_detail primary key (detail_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_calc_task_partition
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_calc_task_partition (
  partition_id               NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  task_id                    NUMBER(19)          not null,
  task_no                    VARCHAR2(64 CHAR)     not null,
  partition_no               NUMBER(10)             not null,
  start_item_no              NUMBER(10)             DEFAULT 1 NOT NULL,
  end_item_no                NUMBER(10)             DEFAULT 1 NOT NULL,
  partition_status           VARCHAR2(32 CHAR)     DEFAULT 'INIT' NOT NULL,
  total_count                NUMBER(10)             DEFAULT 0 NOT NULL,
  processed_count            NUMBER(10)             DEFAULT 0 NOT NULL,
  success_count              NUMBER(10)             DEFAULT 0 NOT NULL,
  fail_count                 NUMBER(10)             DEFAULT 0 NOT NULL,
  amount_total               NUMBER(18,2)   DEFAULT 0.00 NOT NULL,
  persist_mode               VARCHAR2(32 CHAR)     DEFAULT 'BATCH' NOT NULL,
  recovery_hint              VARCHAR2(500 CHAR)    DEFAULT NULL NOT NULL,
  last_error_stage           VARCHAR2(64 CHAR)     DEFAULT NULL NOT NULL,
  execute_node               VARCHAR2(64 CHAR)     default null,
  claim_time                 TIMESTAMP(6)        default null,
  started_time               TIMESTAMP(6)        default null,
  finished_time              TIMESTAMP(6)        default null,
  duration_ms                NUMBER(19)          default 0,
  last_error                 VARCHAR2(1000 CHAR)   DEFAULT NULL,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  update_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_calc_task_partition unique (task_id, partition_no),
  constraint fk_cost_calc_task_partition_task foreign key (task_id) references cost_calc_task (task_id),
  constraint pk_cost_calc_task_partition primary key (partition_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_result_ledger
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_result_ledger (
  result_id                  NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  task_id                    NUMBER(19)          not null,
  task_no                    VARCHAR2(64 CHAR)     not null,
  scene_id                   NUMBER(19)          not null,
  version_id                 NUMBER(19)          not null,
  fee_id                     NUMBER(19)          not null,
  fee_code                   VARCHAR2(64 CHAR)     not null,
  fee_name                   VARCHAR2(128 CHAR)    not null,
  biz_no                     VARCHAR2(128 CHAR)    not null,
  bill_month                 VARCHAR2(16 CHAR)     not null,
  object_dimension           VARCHAR2(64 CHAR)     DEFAULT NULL,
  object_code                VARCHAR2(128 CHAR)    DEFAULT NULL,
  object_name                VARCHAR2(128 CHAR)    DEFAULT NULL,
  quantity_value             NUMBER(18,4)   default null,
  unit_price                 NUMBER(18,6)   default null,
  amount_value               NUMBER(18,2)   not null,
  currency_code              VARCHAR2(32 CHAR)     default 'CNY',
  result_status              VARCHAR2(32 CHAR)     DEFAULT 'SUCCESS' NOT NULL,
  trace_id                   NUMBER(19)          default null,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint fk_cost_result_task foreign key (task_id) references cost_calc_task (task_id),
  constraint fk_cost_result_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint fk_cost_result_version foreign key (version_id) references cost_publish_version (version_id),
  constraint fk_cost_result_fee foreign key (fee_id) references cost_fee_item (fee_id),
  constraint pk_cost_result_ledger primary key (result_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_result_trace
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_result_trace (
  trace_id                   NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id                   NUMBER(19)          not null,
  version_id                 NUMBER(19)          not null,
  rule_id                    NUMBER(19)          default null,
  tier_id                    NUMBER(19)          default null,
  variable_json              CLOB            default null,
  condition_json             CLOB            default null,
  pricing_json               CLOB            default null,
  timeline_json              CLOB            default null,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint fk_cost_trace_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint fk_cost_trace_version foreign key (version_id) references cost_publish_version (version_id),
  constraint fk_cost_trace_rule foreign key (rule_id) references cost_rule (rule_id),
  constraint fk_cost_trace_tier foreign key (tier_id) references cost_rule_tier (tier_id),
  constraint pk_cost_result_trace primary key (trace_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_open_app
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_open_app (
    app_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    app_code VARCHAR2(64 CHAR) not null,
    app_name VARCHAR2(128 CHAR) not null,
    app_secret_hash CHAR(64 CHAR) not null,
    scene_scope_type VARCHAR2(16 CHAR) DEFAULT 'ALL' NOT NULL,
    scene_ids_json CLOB null,
    allow_draft_snapshot NUMBER(1) DEFAULT 0 NOT NULL,
    token_ttl_seconds NUMBER(10) DEFAULT 7200 NOT NULL,
    effective_start_time TIMESTAMP(6) null,
    effective_end_time TIMESTAMP(6) null,
    status CHAR(1 CHAR) DEFAULT '0' NOT NULL,
    sort_no NUMBER(10) DEFAULT 0,
    create_by VARCHAR2(64 CHAR) null,
    create_time TIMESTAMP(6) null,
    update_by VARCHAR2(64 CHAR) null,
    update_time TIMESTAMP(6) null,
    remark VARCHAR2(500 CHAR) null,
  constraint uk_cost_open_app_code unique (app_code),
  constraint pk_cost_open_app primary key (app_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- Secondary indexes
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_scene_domain_status ON cost_scene (business_domain, status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_scene_org_status ON cost_scene (org_code, status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_fee_scene_status ON cost_fee_item (scene_id, status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_fee_scene_sort ON cost_fee_item (scene_id, sort_no)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_var_group_scene_sort ON cost_variable_group (scene_id, sort_no)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_variable_scene_group ON cost_variable (scene_id, group_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_variable_scene_status ON cost_variable (scene_id, status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_variable_scene_source ON cost_variable (scene_id, source_type, source_system)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_variable_scene_formula ON cost_variable (scene_id, formula_code)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_fee_var_scene_fee ON cost_fee_variable_rel (scene_id, fee_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_fee_var_scene_var ON cost_fee_variable_rel (scene_id, variable_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_fee_var_source ON cost_fee_variable_rel (source_type, source_rule_id, source_code)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_rule_scene_fee ON cost_rule (scene_id, fee_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_rule_scene_status_priority ON cost_rule (scene_id, status, priority)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_rule_scene_formula ON cost_rule (scene_id, amount_formula_code)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_rule_cond_rule_group ON cost_rule_condition (rule_id, group_no, sort_no)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_rule_cond_scene_var ON cost_rule_condition (scene_id, variable_code)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_rule_tier_rule_no ON cost_rule_tier (rule_id, tier_no)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_rule_tier_scene_rule ON cost_rule_tier (scene_id, rule_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_formula_scene_status ON cost_formula (scene_id, status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_formula_version_scene ON cost_formula_version (scene_id, formula_code)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_formula_version_formula ON cost_formula_version (formula_id, create_time)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_publish_scene_status ON cost_publish_version (scene_id, version_status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_publish_scene_time ON cost_publish_version (scene_id, published_time)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_snapshot_version_type ON cost_publish_snapshot (version_id, snapshot_type)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_snapshot_version_code ON cost_publish_snapshot (version_id, object_code)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_simulation_scene_time ON cost_simulation_record (scene_id, create_time)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_audit_scene_time ON cost_audit_log (scene_id, operate_time)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_audit_object ON cost_audit_log (object_type, object_code)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_audit_action ON cost_audit_log (action_type, operate_time)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_bill_period_status ON cost_bill_period (period_status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_bill_period_version ON cost_bill_period (active_version_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_recalc_scene_month ON cost_recalc_order (scene_id, bill_month)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_recalc_status ON cost_recalc_order (recalc_status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_recalc_target_task ON cost_recalc_order (target_task_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_alarm_scene_time ON cost_alarm_record (scene_id, trigger_time)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_alarm_task ON cost_alarm_record (task_id, detail_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_alarm_status ON cost_alarm_record (alarm_status, alarm_level)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_alarm_source_status ON cost_alarm_record (source_key, alarm_status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_access_profile_fee ON cost_access_profile (fee_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_access_profile_status ON cost_access_profile (status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_input_batch_scene_month ON cost_calc_input_batch (scene_id, bill_month)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_input_batch_item_batch ON cost_calc_input_batch_item (batch_id, item_no)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_task_scene_month ON cost_calc_task (scene_id, bill_month)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_task_scene_status ON cost_calc_task (scene_id, task_status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_task_version ON cost_calc_task (version_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_task_detail_task_status ON cost_calc_task_detail (task_id, detail_status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_task_detail_task_partition ON cost_calc_task_detail (task_id, partition_no)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_task_detail_task_no ON cost_calc_task_detail (task_no)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_task_partition_task_status ON cost_calc_task_partition (task_id, partition_status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_task_partition_task_no ON cost_calc_task_partition (task_no)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_task_partition_status_claim ON cost_calc_task_partition (partition_status, claim_time)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_result_scene_month ON cost_result_ledger (scene_id, bill_month)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_result_task_fee ON cost_result_ledger (task_id, fee_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_result_biz_fee ON cost_result_ledger (biz_no, fee_code)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_result_version ON cost_result_ledger (version_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_trace_scene_ver ON cost_result_trace (scene_id, version_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_trace_rule ON cost_result_trace (rule_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_trace_tier ON cost_result_trace (tier_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_open_app_status ON cost_open_app (status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- End of Cost Lite Oracle schema baseline.
