-- Cost Lite Oracle schema baseline
-- Generated from the frozen MySQL entity baseline; no DROP statements are used.
-- Oracle 12c+ / 19c / 23ai. Empty strings are represented by Oracle as NULL.

-- =========================================================
-- cost_scene
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_scene (
  scene_id                  NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_code                VARCHAR2(64 CHAR)     not null,
  scene_name                VARCHAR2(128 CHAR)    not null,
  business_domain           VARCHAR2(64 CHAR)     not null,
  org_code                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  scene_type                VARCHAR2(32 CHAR)     default 'CONTRACT',
  active_version_id         NUMBER(19)          default null,
  default_object_dimension  VARCHAR2(64 CHAR)     DEFAULT NULL,
  status                    CHAR(1 CHAR)         DEFAULT '0' NOT NULL,
  remark                    VARCHAR2(500 CHAR)    default null,
  create_by                 VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time               TIMESTAMP(6)        default SYSTIMESTAMP,
  update_by                 VARCHAR2(64 CHAR)     DEFAULT NULL,
  update_time               TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_scene_code unique (scene_code),
  constraint pk_cost_scene primary key (scene_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_fee_item
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_fee_item (
  fee_id                    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id                  NUMBER(19)          not null,
  fee_code                  VARCHAR2(64 CHAR)     not null,
  fee_name                  VARCHAR2(128 CHAR)    not null,
  fee_category              VARCHAR2(64 CHAR)     DEFAULT NULL,
  unit_code                 VARCHAR2(32 CHAR)     DEFAULT NULL,
  factor_summary            VARCHAR2(255 CHAR)    DEFAULT NULL,
  scope_description         VARCHAR2(255 CHAR)    DEFAULT NULL,
  object_dimension          VARCHAR2(64 CHAR)     DEFAULT NULL,
  sort_no                   NUMBER(10)             DEFAULT 0 NOT NULL,
  status                    CHAR(1 CHAR)         DEFAULT '0' NOT NULL,
  remark                    VARCHAR2(500 CHAR)    default null,
  create_by                 VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time               TIMESTAMP(6)        default SYSTIMESTAMP,
  update_by                 VARCHAR2(64 CHAR)     DEFAULT NULL,
  update_time               TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_fee_scene_code unique (scene_id, fee_code),
  constraint fk_cost_fee_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint pk_cost_fee_item primary key (fee_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_variable_group
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_variable_group (
  group_id                  NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id                  NUMBER(19)          not null,
  group_code                VARCHAR2(64 CHAR)     not null,
  group_name                VARCHAR2(128 CHAR)    not null,
  sort_no                   NUMBER(10)             DEFAULT 0 NOT NULL,
  status                    CHAR(1 CHAR)         DEFAULT '0' NOT NULL,
  remark                    VARCHAR2(500 CHAR)    default null,
  create_by                 VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time               TIMESTAMP(6)        default SYSTIMESTAMP,
  update_by                 VARCHAR2(64 CHAR)     DEFAULT NULL,
  update_time               TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_var_group_scene_code unique (scene_id, group_code),
  constraint fk_cost_var_group_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint pk_cost_variable_group primary key (group_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_variable
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_variable (
  variable_id               NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id                  NUMBER(19)          not null,
  group_id                  NUMBER(19)          default null,
  variable_code             VARCHAR2(64 CHAR)     not null,
  variable_name             VARCHAR2(128 CHAR)    not null,
  variable_type             VARCHAR2(32 CHAR)     not null,
  source_type               VARCHAR2(32 CHAR)     not null,
  source_system             VARCHAR2(64 CHAR)     DEFAULT NULL,
  dict_type                 VARCHAR2(64 CHAR)     DEFAULT NULL,
  remote_api                VARCHAR2(255 CHAR)    DEFAULT NULL,
  request_method            VARCHAR2(16 CHAR)     default 'GET',
  content_type              VARCHAR2(128 CHAR)    default 'application/json',
  query_config_json         CLOB            default null,
  request_headers_json      CLOB            default null,
  body_template_json        CLOB            default null,
  auth_type                 VARCHAR2(32 CHAR)     default 'NONE',
  auth_config_json          CLOB            default null,
  data_path                 VARCHAR2(255 CHAR)    DEFAULT NULL,
  response_config_json      CLOB            default null,
  mapping_config_json       CLOB            default null,
  page_config_json          CLOB            default null,
  sync_mode                 VARCHAR2(32 CHAR)     default 'REALTIME',
  cache_policy              VARCHAR2(32 CHAR)     default 'MANUAL_REFRESH',
  fallback_policy           VARCHAR2(32 CHAR)     default 'FAIL_FAST',
  adapter_type              VARCHAR2(32 CHAR)     default 'STANDARD',
  adapter_config_json       CLOB            default null,
  formula_expr              VARCHAR2(2000 CHAR)   default null,
  formula_code              VARCHAR2(64 CHAR)     DEFAULT NULL,
  data_type                 VARCHAR2(32 CHAR)     default 'STRING',
  default_value             VARCHAR2(255 CHAR)    DEFAULT NULL,
  precision_scale           NUMBER(10)             default 2,
  status                    CHAR(1 CHAR)         DEFAULT '0' NOT NULL,
  sort_no                   NUMBER(10)             DEFAULT 0 NOT NULL,
  remark                    VARCHAR2(500 CHAR)    default null,
  create_by                 VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time               TIMESTAMP(6)        default SYSTIMESTAMP,
  update_by                 VARCHAR2(64 CHAR)     DEFAULT NULL,
  update_time               TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_variable_scene_code unique (scene_id, variable_code),
  constraint fk_cost_variable_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint fk_cost_variable_group foreign key (group_id) references cost_variable_group (group_id),
  constraint pk_cost_variable primary key (variable_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_fee_variable_rel
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_fee_variable_rel (
  rel_id                    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id                  NUMBER(19)          not null,
  fee_id                    NUMBER(19)          not null,
  variable_id               NUMBER(19)          not null,
  relation_type             VARCHAR2(32 CHAR)     DEFAULT 'OPTIONAL' NOT NULL,
  source_type               VARCHAR2(32 CHAR)     DEFAULT 'RULE_DERIVED' NOT NULL,
  source_rule_id            NUMBER(19)          default null,
  source_code               VARCHAR2(128 CHAR)    DEFAULT NULL NOT NULL,
  sort_no                   NUMBER(10)             DEFAULT 0 NOT NULL,
  remark                    VARCHAR2(500 CHAR)    default null,
  create_by                 VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time               TIMESTAMP(6)        default SYSTIMESTAMP,
  update_by                 VARCHAR2(64 CHAR)     DEFAULT NULL,
  update_time               TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_fee_var_rel unique (fee_id, variable_id, relation_type, source_type, source_code),
  constraint fk_cost_fee_var_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint fk_cost_fee_var_fee foreign key (fee_id) references cost_fee_item (fee_id),
  constraint fk_cost_fee_var_variable foreign key (variable_id) references cost_variable (variable_id),
  constraint pk_cost_fee_variable_rel primary key (rel_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_rule
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_rule (
  rule_id                    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id                   NUMBER(19)          not null,
  fee_id                     NUMBER(19)          not null,
  rule_code                  VARCHAR2(64 CHAR)     not null,
  rule_name                  VARCHAR2(128 CHAR)    DEFAULT NULL,
  rule_type                  VARCHAR2(32 CHAR)     not null,
  condition_logic            VARCHAR2(16 CHAR)     DEFAULT 'AND' NOT NULL,
  priority                   NUMBER(10)             DEFAULT 0 NOT NULL,
  quantity_variable_code     VARCHAR2(64 CHAR)     DEFAULT NULL,
  pricing_mode               VARCHAR2(32 CHAR)     DEFAULT 'TYPED' NOT NULL,
  pricing_json               CLOB            default null,
  amount_formula             VARCHAR2(2000 CHAR)   default null,
  amount_formula_code        VARCHAR2(64 CHAR)     DEFAULT NULL,
  note_template              VARCHAR2(500 CHAR)    DEFAULT NULL,
  status                     CHAR(1 CHAR)         DEFAULT '0' NOT NULL,
  sort_no                    NUMBER(10)             DEFAULT 0 NOT NULL,
  remark                     VARCHAR2(500 CHAR)    default null,
  create_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  update_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  update_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_rule_scene_code unique (scene_id, rule_code),
  constraint fk_cost_rule_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint fk_cost_rule_fee foreign key (fee_id) references cost_fee_item (fee_id),
  constraint pk_cost_rule primary key (rule_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_rule_condition
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_rule_condition (
  condition_id               NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id                   NUMBER(19)          not null,
  rule_id                    NUMBER(19)          not null,
  group_no                   NUMBER(10)             DEFAULT 1 NOT NULL,
  sort_no                    NUMBER(10)             DEFAULT 0 NOT NULL,
  variable_code              VARCHAR2(64 CHAR)     not null,
  display_name               VARCHAR2(128 CHAR)    DEFAULT NULL,
  operator_code              VARCHAR2(32 CHAR)     not null,
  compare_value              VARCHAR2(1000 CHAR)   DEFAULT NULL,
  status                     CHAR(1 CHAR)         DEFAULT '0' NOT NULL,
  remark                     VARCHAR2(500 CHAR)    default null,
  create_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  update_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  update_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint fk_cost_rule_condition_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint fk_cost_rule_condition_rule foreign key (rule_id) references cost_rule (rule_id),
  constraint pk_cost_rule_condition primary key (condition_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_rule_tier
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_rule_tier (
  tier_id                    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id                   NUMBER(19)          not null,
  rule_id                    NUMBER(19)          not null,
  start_value                NUMBER(18,4)   default null,
  end_value                  NUMBER(18,4)   default null,
  rate_value                 NUMBER(18,6)   not null,
  interval_mode              VARCHAR2(32 CHAR)     DEFAULT 'LEFT_CLOSED_RIGHT_OPEN' NOT NULL,
  tier_no                    NUMBER(10)             DEFAULT 1 NOT NULL,
  status                     CHAR(1 CHAR)         DEFAULT '0' NOT NULL,
  remark                     VARCHAR2(500 CHAR)    default null,
  create_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  update_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  update_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint fk_cost_rule_tier_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint fk_cost_rule_tier_rule foreign key (rule_id) references cost_rule (rule_id),
  constraint pk_cost_rule_tier primary key (tier_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_formula
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_formula (
    formula_id             NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    scene_id               NUMBER(19)          not null,
    formula_code           VARCHAR2(64 CHAR)     not null,
    formula_name           VARCHAR2(128 CHAR)    not null,
    formula_desc           VARCHAR2(500 CHAR)    DEFAULT NULL,
    business_formula       VARCHAR2(1000 CHAR)   DEFAULT NULL,
    formula_expr           VARCHAR2(2000 CHAR)   not null,
    asset_type             VARCHAR2(32 CHAR)     default 'FORMULA',
    workbench_mode         VARCHAR2(32 CHAR)     default 'GUIDED',
    workbench_pattern      VARCHAR2(32 CHAR)     default 'IF_ELSE',
    template_code          VARCHAR2(64 CHAR)     DEFAULT NULL,
    workbench_config_json  CLOB            default null,
    namespace_scope        VARCHAR2(128 CHAR)    default 'V,C,I,F,T',
    return_type            VARCHAR2(32 CHAR)     default 'NUMBER',
    test_case_json         CLOB            default null,
    sample_result_json     CLOB            default null,
    last_test_time         TIMESTAMP(6)        default null,
    status                 CHAR(1 CHAR)         default '0',
    sort_no                NUMBER(10)             default 10,
    remark                 VARCHAR2(500 CHAR)    DEFAULT NULL,
    create_by              VARCHAR2(64 CHAR)     DEFAULT NULL,
    create_time            TIMESTAMP(6)        default SYSTIMESTAMP,
    update_by              VARCHAR2(64 CHAR)     DEFAULT NULL,
    update_time            TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_formula_scene_code unique (scene_id, formula_code),
  constraint pk_cost_formula primary key (formula_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_formula_version
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_formula_version (
    version_id             NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    formula_id             NUMBER(19)          not null,
    scene_id               NUMBER(19)          not null,
    formula_code           VARCHAR2(64 CHAR)     not null,
    formula_name           VARCHAR2(128 CHAR)    not null,
    asset_type             VARCHAR2(32 CHAR)     default 'FORMULA',
    version_no             NUMBER(10)             not null,
    change_type            VARCHAR2(32 CHAR)     default 'UPDATE',
    business_formula       VARCHAR2(1000 CHAR)   DEFAULT NULL,
    formula_expr           VARCHAR2(2000 CHAR)   DEFAULT NULL,
    workbench_mode         VARCHAR2(32 CHAR)     default 'GUIDED',
    workbench_pattern      VARCHAR2(32 CHAR)     default 'IF_ELSE',
    template_code          VARCHAR2(64 CHAR)     DEFAULT NULL,
    workbench_config_json  CLOB            default null,
    snapshot_json          CLOB            default null,
    create_by              VARCHAR2(64 CHAR)     DEFAULT NULL,
    create_time            TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_formula_version_no unique (formula_id, version_no),
  constraint pk_cost_formula_version primary key (version_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_publish_version
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_publish_version (
  version_id                 NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id                   NUMBER(19)          not null,
  version_no                 VARCHAR2(64 CHAR)     not null,
  version_status             VARCHAR2(32 CHAR)     DEFAULT 'PUBLISHED' NOT NULL,
  publish_desc               VARCHAR2(1000 CHAR)   DEFAULT NULL,
  validation_result_json     CLOB            default null,
  snapshot_hash              VARCHAR2(128 CHAR)    DEFAULT NULL,
  published_by               VARCHAR2(64 CHAR)     DEFAULT NULL,
  published_time             TIMESTAMP(6)        default null,
  activated_by               VARCHAR2(64 CHAR)     DEFAULT NULL,
  activated_time             TIMESTAMP(6)        default null,
  rollback_by                VARCHAR2(64 CHAR)     DEFAULT NULL,
  rollback_time              TIMESTAMP(6)        default null,
  create_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  update_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  update_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_publish_scene_ver unique (scene_id, version_no),
  constraint fk_cost_publish_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint pk_cost_publish_version primary key (version_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_publish_snapshot
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_publish_snapshot (
  snapshot_id                NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  version_id                 NUMBER(19)          not null,
  snapshot_type              VARCHAR2(32 CHAR)     not null,
  object_code                VARCHAR2(64 CHAR)     not null,
  object_name                VARCHAR2(128 CHAR)    DEFAULT NULL,
  snapshot_json              CLOB            not null,
  sort_no                    NUMBER(10)             DEFAULT 0 NOT NULL,
  create_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint fk_cost_snapshot_version foreign key (version_id) references cost_publish_version (version_id),
  constraint pk_cost_publish_snapshot primary key (snapshot_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_simulation_record
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_simulation_record (
  simulation_id              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id                   NUMBER(19)          not null,
  version_id                 NUMBER(19)          default null,
  bill_month                 VARCHAR2(16 CHAR)     DEFAULT NULL NOT NULL,
  simulation_no              VARCHAR2(64 CHAR)     not null,
  input_json                 CLOB            not null,
  variable_json              CLOB            default null,
  explain_json               CLOB            default null,
  result_json                CLOB            default null,
  status                     VARCHAR2(32 CHAR)     DEFAULT 'SUCCESS' NOT NULL,
  error_message              VARCHAR2(1000 CHAR)   DEFAULT NULL,
  create_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_simulation_no unique (simulation_no),
  constraint fk_cost_simulation_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint fk_cost_simulation_version foreign key (version_id) references cost_publish_version (version_id),
  constraint pk_cost_simulation_record primary key (simulation_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_audit_log
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_audit_log (
  audit_id                   NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id                   NUMBER(19)          default null,
  object_type                VARCHAR2(32 CHAR)     not null,
  object_code                VARCHAR2(64 CHAR)     DEFAULT NULL,
  action_type                VARCHAR2(32 CHAR)     not null,
  action_summary             VARCHAR2(500 CHAR)    DEFAULT NULL,
  before_json                CLOB            default null,
  after_json                 CLOB            default null,
  operator_code              VARCHAR2(64 CHAR)     DEFAULT NULL,
  operator_name              VARCHAR2(128 CHAR)    DEFAULT NULL,
  operate_time               TIMESTAMP(6)        default SYSTIMESTAMP,
  request_no                 VARCHAR2(64 CHAR)     DEFAULT NULL,
  constraint pk_cost_audit_log primary key (audit_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_bill_period
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_bill_period (
  period_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id NUMBER(19) not null,
  bill_month VARCHAR2(7 CHAR) not null,
  period_status VARCHAR2(32 CHAR) DEFAULT 'NOT_STARTED' NOT NULL,
  active_version_id NUMBER(19) default null,
  result_count NUMBER(19) DEFAULT 0 NOT NULL,
  amount_total NUMBER(18,2) DEFAULT 0.00 NOT NULL,
  last_task_id NUMBER(19) default null,
  last_task_no VARCHAR2(64 CHAR) DEFAULT NULL,
  sealed_by VARCHAR2(64 CHAR) DEFAULT NULL,
  sealed_time TIMESTAMP(6) default null,
  create_by VARCHAR2(64 CHAR) DEFAULT NULL,
  create_time TIMESTAMP(6) default SYSTIMESTAMP,
  update_by VARCHAR2(64 CHAR) DEFAULT NULL,
  update_time TIMESTAMP(6) default SYSTIMESTAMP,
  remark VARCHAR2(500 CHAR) DEFAULT NULL,
  constraint uk_cost_bill_period_scene_month unique (scene_id, bill_month),
  constraint pk_cost_bill_period primary key (period_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_recalc_order
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_recalc_order (
  recalc_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id NUMBER(19) not null,
  bill_month VARCHAR2(7 CHAR) not null,
  version_id NUMBER(19) not null,
  period_id NUMBER(19) default null,
  baseline_task_id NUMBER(19) default null,
  baseline_task_no VARCHAR2(64 CHAR) DEFAULT NULL,
  target_task_id NUMBER(19) default null,
  target_task_no VARCHAR2(64 CHAR) DEFAULT NULL,
  recalc_status VARCHAR2(32 CHAR) DEFAULT 'PENDING_APPROVAL' NOT NULL,
  apply_reason VARCHAR2(500 CHAR) DEFAULT NULL,
  approve_opinion VARCHAR2(500 CHAR) DEFAULT NULL,
  diff_summary_json CLOB default null,
  diff_amount NUMBER(18,2) DEFAULT 0.00 NOT NULL,
  request_no VARCHAR2(64 CHAR) DEFAULT NULL,
  approve_by VARCHAR2(64 CHAR) DEFAULT NULL,
  approve_time TIMESTAMP(6) default null,
  execute_by VARCHAR2(64 CHAR) DEFAULT NULL,
  execute_time TIMESTAMP(6) default null,
  finish_time TIMESTAMP(6) default null,
  create_by VARCHAR2(64 CHAR) DEFAULT NULL,
  create_time TIMESTAMP(6) default SYSTIMESTAMP,
  update_by VARCHAR2(64 CHAR) DEFAULT NULL,
  update_time TIMESTAMP(6) default SYSTIMESTAMP,
  remark VARCHAR2(500 CHAR) DEFAULT NULL,
  constraint pk_cost_recalc_order primary key (recalc_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_alarm_record
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_alarm_record (
  alarm_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id NUMBER(19) default null,
  version_id NUMBER(19) default null,
  task_id NUMBER(19) default null,
  detail_id NUMBER(19) default null,
  bill_month VARCHAR2(7 CHAR) DEFAULT NULL,
  alarm_type VARCHAR2(32 CHAR) not null,
  alarm_level VARCHAR2(32 CHAR) DEFAULT 'WARN' NOT NULL,
  alarm_status VARCHAR2(32 CHAR) DEFAULT 'OPEN' NOT NULL,
  source_key VARCHAR2(128 CHAR) DEFAULT NULL,
  alarm_title VARCHAR2(200 CHAR) DEFAULT NULL,
  alarm_content VARCHAR2(1000 CHAR) DEFAULT NULL,
  trigger_time TIMESTAMP(6) default SYSTIMESTAMP,
  first_trigger_time TIMESTAMP(6) null,
  latest_trigger_time TIMESTAMP(6) null,
  occurrence_count NUMBER(10) DEFAULT 1 NOT NULL,
  ack_by VARCHAR2(64 CHAR) DEFAULT NULL,
  ack_time TIMESTAMP(6) default null,
  resolve_by VARCHAR2(64 CHAR) DEFAULT NULL,
  resolve_time TIMESTAMP(6) default null,
  create_by VARCHAR2(64 CHAR) DEFAULT NULL,
  create_time TIMESTAMP(6) default SYSTIMESTAMP,
  update_by VARCHAR2(64 CHAR) DEFAULT NULL,
  update_time TIMESTAMP(6) default SYSTIMESTAMP,
  remark VARCHAR2(500 CHAR) DEFAULT NULL,
  constraint pk_cost_alarm_record primary key (alarm_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_access_profile
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_access_profile (
    profile_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    scene_id NUMBER(19) not null,
    fee_id NUMBER(19) null,
    fee_scope_type VARCHAR2(16 CHAR) DEFAULT 'ALL' NOT NULL,
    fee_ids_json CLOB null,
    version_id NUMBER(19) null,
    profile_code VARCHAR2(64 CHAR) not null,
    profile_name VARCHAR2(128 CHAR) not null,
    source_type VARCHAR2(32 CHAR) DEFAULT 'RAW_JSON' NOT NULL,
    task_type VARCHAR2(32 CHAR) DEFAULT 'FORMAL_BATCH' NOT NULL,
    request_method VARCHAR2(16 CHAR) DEFAULT 'GET' NOT NULL,
    endpoint_url VARCHAR2(255 CHAR) null,
    auth_type VARCHAR2(32 CHAR) DEFAULT 'NONE' NOT NULL,
    auth_config_json CLOB null,
    fetch_config_json CLOB null,
    mapping_json CLOB null,
    sample_payload_json CLOB null,
    sample_input_json CLOB null,
    status CHAR(1 CHAR) DEFAULT '0' NOT NULL,
    sort_no NUMBER(10) DEFAULT 0,
    create_by VARCHAR2(64 CHAR) null,
    create_time TIMESTAMP(6) null,
    update_by VARCHAR2(64 CHAR) null,
    update_time TIMESTAMP(6) null,
    remark VARCHAR2(500 CHAR) null,
  constraint uk_cost_access_profile_scene_code unique (scene_id, profile_code),
  constraint pk_cost_access_profile primary key (profile_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_calc_input_batch
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_calc_input_batch (
  batch_id                   NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  batch_no                   VARCHAR2(64 CHAR)     not null,
  scene_id                   NUMBER(19)          not null,
  version_id                 NUMBER(19)          default null,
  bill_month                 VARCHAR2(16 CHAR)     DEFAULT NULL NOT NULL,
  source_type                VARCHAR2(32 CHAR)     DEFAULT 'JSON_IMPORT' NOT NULL,
  batch_status               VARCHAR2(32 CHAR)     DEFAULT 'READY' NOT NULL,
  total_count                NUMBER(10)             DEFAULT 0 NOT NULL,
  valid_count                NUMBER(10)             DEFAULT 0 NOT NULL,
  error_count                NUMBER(10)             DEFAULT 0 NOT NULL,
  remark                     VARCHAR2(500 CHAR)    default null,
  error_message              VARCHAR2(1000 CHAR)   DEFAULT NULL,
  access_profile_id          NUMBER(19)          null,
  checkpoint_json            CLOB        null,
  create_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  update_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  update_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_calc_input_batch_no unique (batch_no),
  constraint fk_cost_calc_input_batch_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint fk_cost_calc_input_batch_version foreign key (version_id) references cost_publish_version (version_id),
  constraint pk_cost_calc_input_batch primary key (batch_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_calc_input_batch_item
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_calc_input_batch_item (
  item_id                    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  batch_id                   NUMBER(19)          not null,
  batch_no                   VARCHAR2(64 CHAR)     not null,
  item_no                    NUMBER(10)             not null,
  biz_no                     VARCHAR2(128 CHAR)    not null,
  item_status                VARCHAR2(32 CHAR)     DEFAULT 'READY' NOT NULL,
  input_json                 CLOB            not null,
  error_message              VARCHAR2(1000 CHAR)   DEFAULT NULL,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  update_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_calc_input_batch_item unique (batch_id, biz_no),
  constraint fk_cost_calc_input_batch_item_batch foreign key (batch_id) references cost_calc_input_batch (batch_id),
  constraint pk_cost_calc_input_batch_item primary key (item_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_calc_task
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_calc_task (
  task_id                    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  task_no                    VARCHAR2(64 CHAR)     not null,
  scene_id                   NUMBER(19)          not null,
  version_id                 NUMBER(19)          not null,
  task_type                  VARCHAR2(32 CHAR)     not null,
  bill_month                 VARCHAR2(16 CHAR)     DEFAULT NULL,
  source_count               NUMBER(10)             DEFAULT 0 NOT NULL,
  success_count              NUMBER(10)             DEFAULT 0 NOT NULL,
  fail_count                 NUMBER(10)             DEFAULT 0 NOT NULL,
  task_status                VARCHAR2(32 CHAR)     DEFAULT 'INIT' NOT NULL,
  progress_percent           NUMBER(5,2)    DEFAULT 0 NOT NULL,
  started_time               TIMESTAMP(6)        default null,
  finished_time              TIMESTAMP(6)        default null,
  duration_ms                NUMBER(19)          default 0,
  request_no                 VARCHAR2(64 CHAR)     DEFAULT NULL,
  request_no_key             GENERATED ALWAYS AS (CAST(request_no AS VARCHAR2(64 CHAR))) VIRTUAL,
  execute_node               VARCHAR2(128 CHAR)    DEFAULT NULL,
  input_source_type          VARCHAR2(32 CHAR)     DEFAULT 'INLINE_JSON' NOT NULL,
  source_batch_no            VARCHAR2(64 CHAR)     DEFAULT NULL,
  error_message              VARCHAR2(1000 CHAR)   DEFAULT NULL,
  remark                     VARCHAR2(500 CHAR)    default null,
  create_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  update_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  update_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_calc_task_no unique (task_no),
  constraint uk_cost_calc_task_request_no unique (scene_id, version_id, bill_month, request_no_key),
  constraint fk_cost_calc_task_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint fk_cost_calc_task_version foreign key (version_id) references cost_publish_version (version_id),
  constraint pk_cost_calc_task primary key (task_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_calc_task_detail
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_calc_task_detail (
  detail_id                  NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  task_id                    NUMBER(19)          not null,
  task_no                    VARCHAR2(64 CHAR)     not null,
  biz_no                     VARCHAR2(128 CHAR)    not null,
  partition_no               NUMBER(10)             DEFAULT 1 NOT NULL,
  detail_status              VARCHAR2(32 CHAR)     DEFAULT 'INIT' NOT NULL,
  retry_count                NUMBER(10)             DEFAULT 0 NOT NULL,
  input_json                 CLOB            not null,
  result_summary             VARCHAR2(1000 CHAR)   DEFAULT NULL,
  error_message              VARCHAR2(1000 CHAR)   DEFAULT NULL,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  update_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_calc_task_detail unique (task_id, biz_no),
  constraint fk_cost_calc_task_detail_task foreign key (task_id) references cost_calc_task (task_id),
  constraint pk_cost_calc_task_detail primary key (detail_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_calc_task_partition
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_calc_task_partition (
  partition_id               NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  task_id                    NUMBER(19)          not null,
  task_no                    VARCHAR2(64 CHAR)     not null,
  partition_no               NUMBER(10)             not null,
  start_item_no              NUMBER(10)             DEFAULT 1 NOT NULL,
  end_item_no                NUMBER(10)             DEFAULT 1 NOT NULL,
  partition_status           VARCHAR2(32 CHAR)     DEFAULT 'INIT' NOT NULL,
  total_count                NUMBER(10)             DEFAULT 0 NOT NULL,
  processed_count            NUMBER(10)             DEFAULT 0 NOT NULL,
  success_count              NUMBER(10)             DEFAULT 0 NOT NULL,
  fail_count                 NUMBER(10)             DEFAULT 0 NOT NULL,
  amount_total               NUMBER(18,2)   DEFAULT 0.00 NOT NULL,
  persist_mode               VARCHAR2(32 CHAR)     DEFAULT 'BATCH' NOT NULL,
  recovery_hint              VARCHAR2(500 CHAR)    DEFAULT NULL NOT NULL,
  last_error_stage           VARCHAR2(64 CHAR)     DEFAULT NULL NOT NULL,
  execute_node               VARCHAR2(64 CHAR)     default null,
  claim_time                 TIMESTAMP(6)        default null,
  started_time               TIMESTAMP(6)        default null,
  finished_time              TIMESTAMP(6)        default null,
  duration_ms                NUMBER(19)          default 0,
  last_error                 VARCHAR2(1000 CHAR)   DEFAULT NULL,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  update_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_calc_task_partition unique (task_id, partition_no),
  constraint fk_cost_calc_task_partition_task foreign key (task_id) references cost_calc_task (task_id),
  constraint pk_cost_calc_task_partition primary key (partition_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_result_ledger
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_result_ledger (
  result_id                  NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  task_id                    NUMBER(19)          not null,
  task_no                    VARCHAR2(64 CHAR)     not null,
  scene_id                   NUMBER(19)          not null,
  version_id                 NUMBER(19)          not null,
  fee_id                     NUMBER(19)          not null,
  fee_code                   VARCHAR2(64 CHAR)     not null,
  fee_name                   VARCHAR2(128 CHAR)    not null,
  biz_no                     VARCHAR2(128 CHAR)    not null,
  bill_month                 VARCHAR2(16 CHAR)     not null,
  object_dimension           VARCHAR2(64 CHAR)     DEFAULT NULL,
  object_code                VARCHAR2(128 CHAR)    DEFAULT NULL,
  object_name                VARCHAR2(128 CHAR)    DEFAULT NULL,
  quantity_value             NUMBER(18,4)   default null,
  unit_price                 NUMBER(18,6)   default null,
  amount_value               NUMBER(18,2)   not null,
  currency_code              VARCHAR2(32 CHAR)     default 'CNY',
  result_status              VARCHAR2(32 CHAR)     DEFAULT 'SUCCESS' NOT NULL,
  trace_id                   NUMBER(19)          default null,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint fk_cost_result_task foreign key (task_id) references cost_calc_task (task_id),
  constraint fk_cost_result_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint fk_cost_result_version foreign key (version_id) references cost_publish_version (version_id),
  constraint fk_cost_result_fee foreign key (fee_id) references cost_fee_item (fee_id),
  constraint pk_cost_result_ledger primary key (result_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_result_trace
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_result_trace (
  trace_id                   NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id                   NUMBER(19)          not null,
  version_id                 NUMBER(19)          not null,
  rule_id                    NUMBER(19)          default null,
  tier_id                    NUMBER(19)          default null,
  variable_json              CLOB            default null,
  condition_json             CLOB            default null,
  pricing_json               CLOB            default null,
  timeline_json              CLOB            default null,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint fk_cost_trace_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint fk_cost_trace_version foreign key (version_id) references cost_publish_version (version_id),
  constraint fk_cost_trace_rule foreign key (rule_id) references cost_rule (rule_id),
  constraint fk_cost_trace_tier foreign key (tier_id) references cost_rule_tier (tier_id),
  constraint pk_cost_result_trace primary key (trace_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_open_app
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_open_app (
    app_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    app_code VARCHAR2(64 CHAR) not null,
    app_name VARCHAR2(128 CHAR) not null,
    app_secret_hash CHAR(64 CHAR) not null,
    scene_scope_type VARCHAR2(16 CHAR) DEFAULT 'ALL' NOT NULL,
    scene_ids_json CLOB null,
    allow_draft_snapshot NUMBER(1) DEFAULT 0 NOT NULL,
    token_ttl_seconds NUMBER(10) DEFAULT 7200 NOT NULL,
    effective_start_time TIMESTAMP(6) null,
    effective_end_time TIMESTAMP(6) null,
    status CHAR(1 CHAR) DEFAULT '0' NOT NULL,
    sort_no NUMBER(10) DEFAULT 0,
    create_by VARCHAR2(64 CHAR) null,
    create_time TIMESTAMP(6) null,
    update_by VARCHAR2(64 CHAR) null,
    update_time TIMESTAMP(6) null,
    remark VARCHAR2(500 CHAR) null,
  constraint uk_cost_open_app_code unique (app_code),
  constraint pk_cost_open_app primary key (app_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- Secondary indexes
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_scene_domain_status ON cost_scene (business_domain, status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_scene_org_status ON cost_scene (org_code, status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_fee_scene_status ON cost_fee_item (scene_id, status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_fee_scene_sort ON cost_fee_item (scene_id, sort_no)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_var_group_scene_sort ON cost_variable_group (scene_id, sort_no)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_variable_scene_group ON cost_variable (scene_id, group_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_variable_scene_status ON cost_variable (scene_id, status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_variable_scene_source ON cost_variable (scene_id, source_type, source_system)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_variable_scene_formula ON cost_variable (scene_id, formula_code)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_fee_var_scene_fee ON cost_fee_variable_rel (scene_id, fee_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_fee_var_scene_var ON cost_fee_variable_rel (scene_id, variable_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_fee_var_source ON cost_fee_variable_rel (source_type, source_rule_id, source_code)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_rule_scene_fee ON cost_rule (scene_id, fee_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_rule_scene_status_priority ON cost_rule (scene_id, status, priority)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_rule_scene_formula ON cost_rule (scene_id, amount_formula_code)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_rule_cond_rule_group ON cost_rule_condition (rule_id, group_no, sort_no)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_rule_cond_scene_var ON cost_rule_condition (scene_id, variable_code)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_rule_tier_rule_no ON cost_rule_tier (rule_id, tier_no)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_rule_tier_scene_rule ON cost_rule_tier (scene_id, rule_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_formula_scene_status ON cost_formula (scene_id, status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_formula_version_scene ON cost_formula_version (scene_id, formula_code)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_formula_version_formula ON cost_formula_version (formula_id, create_time)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_publish_scene_status ON cost_publish_version (scene_id, version_status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_publish_scene_time ON cost_publish_version (scene_id, published_time)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_snapshot_version_type ON cost_publish_snapshot (version_id, snapshot_type)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_snapshot_version_code ON cost_publish_snapshot (version_id, object_code)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_simulation_scene_time ON cost_simulation_record (scene_id, create_time)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_audit_scene_time ON cost_audit_log (scene_id, operate_time)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_audit_object ON cost_audit_log (object_type, object_code)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_audit_action ON cost_audit_log (action_type, operate_time)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_bill_period_status ON cost_bill_period (period_status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_bill_period_version ON cost_bill_period (active_version_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_recalc_scene_month ON cost_recalc_order (scene_id, bill_month)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_recalc_status ON cost_recalc_order (recalc_status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_recalc_target_task ON cost_recalc_order (target_task_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_alarm_scene_time ON cost_alarm_record (scene_id, trigger_time)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_alarm_task ON cost_alarm_record (task_id, detail_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_alarm_status ON cost_alarm_record (alarm_status, alarm_level)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_alarm_source_status ON cost_alarm_record (source_key, alarm_status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_access_profile_fee ON cost_access_profile (fee_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_access_profile_status ON cost_access_profile (status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_input_batch_scene_month ON cost_calc_input_batch (scene_id, bill_month)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_input_batch_item_batch ON cost_calc_input_batch_item (batch_id, item_no)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_task_scene_month ON cost_calc_task (scene_id, bill_month)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_task_scene_status ON cost_calc_task (scene_id, task_status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_task_version ON cost_calc_task (version_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_task_detail_task_status ON cost_calc_task_detail (task_id, detail_status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_task_detail_task_partition ON cost_calc_task_detail (task_id, partition_no)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_task_detail_task_no ON cost_calc_task_detail (task_no)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_task_partition_task_status ON cost_calc_task_partition (task_id, partition_status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_task_partition_task_no ON cost_calc_task_partition (task_no)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_task_partition_status_claim ON cost_calc_task_partition (partition_status, claim_time)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_result_scene_month ON cost_result_ledger (scene_id, bill_month)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_result_task_fee ON cost_result_ledger (task_id, fee_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_result_biz_fee ON cost_result_ledger (biz_no, fee_code)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_result_version ON cost_result_ledger (version_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_trace_scene_ver ON cost_result_trace (scene_id, version_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_trace_rule ON cost_result_trace (rule_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_trace_tier ON cost_result_trace (tier_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_open_app_status ON cost_open_app (status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- Lightweight cost dictionaries only
-- =========================================================
-- Only the two dictionary entities required by the workbench are included.
-- They keep the mother platform contract without bringing other RuoYi sys_* tables.
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE sys_dict_type (
  dict_id       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  dict_name     VARCHAR2(100 CHAR) DEFAULT NULL,
  dict_type     VARCHAR2(100 CHAR) NOT NULL,
  status        CHAR(1 CHAR) DEFAULT '0',
  create_by     VARCHAR2(64 CHAR) DEFAULT NULL,
  create_time   TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  update_by     VARCHAR2(64 CHAR) DEFAULT NULL,
  update_time   TIMESTAMP(6) DEFAULT NULL,
  remark        VARCHAR2(500 CHAR) DEFAULT NULL,
  CONSTRAINT uk_sys_dict_type_type UNIQUE (dict_type),
  CONSTRAINT pk_sys_dict_type PRIMARY KEY (dict_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE sys_dict_data (
  dict_code     NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  dict_sort     NUMBER(10) DEFAULT 0,
  dict_label    VARCHAR2(100 CHAR) DEFAULT NULL,
  dict_value    VARCHAR2(100 CHAR) DEFAULT NULL,
  dict_type     VARCHAR2(100 CHAR) NOT NULL,
  css_class     VARCHAR2(100 CHAR) DEFAULT NULL,
  list_class    VARCHAR2(100 CHAR) DEFAULT NULL,
  is_default    CHAR(1 CHAR) DEFAULT 'N',
  status        CHAR(1 CHAR) DEFAULT '0',
  create_by     VARCHAR2(64 CHAR) DEFAULT NULL,
  create_time   TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  update_by     VARCHAR2(64 CHAR) DEFAULT NULL,
  update_time   TIMESTAMP(6) DEFAULT NULL,
  remark        VARCHAR2(500 CHAR) DEFAULT NULL,
  CONSTRAINT uk_sys_dict_data_type_value UNIQUE (dict_type, dict_value),
  CONSTRAINT pk_sys_dict_data PRIMARY KEY (dict_code)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_sys_dict_data_type ON sys_dict_data (dict_type, dict_sort, status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

MERGE INTO sys_dict_type target
USING (
  SELECT '核算-业务域' dict_name, 'cost_business_domain' dict_type, '场景、费目、要素和规则使用的业务域' remark FROM dual
  UNION ALL SELECT '核算-场景状态', 'cost_scene_status', '场景维护状态' FROM dual
  UNION ALL SELECT '核算-场景类型', 'cost_scene_type', '场景分类' FROM dual
  UNION ALL SELECT '核算-费用状态', 'cost_fee_status', '费目维护状态' FROM dual
  UNION ALL SELECT '核算-计价单位', 'cost_unit_code', '费目计价单位' FROM dual
  UNION ALL SELECT '核算-要素分组状态', 'cost_variable_group_status', '要素分组状态' FROM dual
  UNION ALL SELECT '核算-要素类型', 'cost_variable_type', '要素展示和处理类型' FROM dual
  UNION ALL SELECT '核算-要素来源类型', 'cost_variable_source_type', '要素取值来源' FROM dual
  UNION ALL SELECT '核算-要素数据类型', 'cost_variable_data_type', '要素数据类型' FROM dual
  UNION ALL SELECT '核算-变量鉴权方式', 'cost_variable_auth_type', '远程要素鉴权方式' FROM dual
  UNION ALL SELECT '核算-变量同步方式', 'cost_variable_sync_mode', '远程要素同步方式' FROM dual
  UNION ALL SELECT '核算-变量缓存策略', 'cost_variable_cache_policy', '远程要素缓存策略' FROM dual
  UNION ALL SELECT '核算-变量失败兜底策略', 'cost_variable_fallback_policy', '远程要素失败处理方式' FROM dual
  UNION ALL SELECT '核算-要素状态', 'cost_variable_status', '要素维护状态' FROM dual
  UNION ALL SELECT '核算-公式状态', 'cost_formula_status', '公式资产维护状态' FROM dual
  UNION ALL SELECT '核算-公式返回类型', 'cost_formula_return_type', '公式执行结果类型' FROM dual
  UNION ALL SELECT '核算-规则状态', 'cost_rule_status', '规则维护状态' FROM dual
  UNION ALL SELECT '核算-规则类型', 'cost_rule_type', '规则定价类型' FROM dual
  UNION ALL SELECT '核算-规则条件逻辑', 'cost_rule_condition_logic', '条件组之间的逻辑关系' FROM dual
  UNION ALL SELECT '核算-规则操作符', 'cost_rule_operator', '条件比较操作符' FROM dual
  UNION ALL SELECT '核算-阶梯区间模式', 'cost_rule_interval_mode', '阶梯边界模式' FROM dual
  UNION ALL SELECT '核算-发布版本状态', 'cost_publish_version_status', '发布版本状态' FROM dual
  UNION ALL SELECT '核算-试算状态', 'cost_simulation_status', '同步计费和试算状态' FROM dual
  UNION ALL SELECT '核算-正式任务类型', 'cost_calc_task_type', '正式任务类型' FROM dual
  UNION ALL SELECT '核算-正式任务状态', 'cost_calc_task_status', '正式任务状态' FROM dual
  UNION ALL SELECT '核算-结果状态', 'cost_result_status', '正式结果状态' FROM dual
) seed
ON (target.dict_type = seed.dict_type)
WHEN NOT MATCHED THEN INSERT
  (dict_name, dict_type, status, create_by, create_time, remark)
VALUES
  (seed.dict_name, seed.dict_type, '0', 'cost-lite', SYSTIMESTAMP, seed.remark);

MERGE INTO sys_dict_data target
USING (
  SELECT 1 dict_sort, '薪资结算' dict_label, 'SALARY' dict_value, 'cost_business_domain' dict_type, 'success' list_class, 'N' is_default, '业务域：薪资结算' remark FROM dual
  UNION ALL SELECT 2, '港口作业', 'PORT', 'cost_business_domain', 'primary', 'Y', '业务域：港口作业' FROM dual
  UNION ALL SELECT 3, '仓储结算', 'STORAGE', 'cost_business_domain', 'warning', 'N', '业务域：仓储结算' FROM dual
  UNION ALL SELECT 4, '运输计费', 'TRANSPORT', 'cost_business_domain', 'info', 'N', '业务域：运输计费' FROM dual
  UNION ALL SELECT 5, '材料成本', 'MATERIAL', 'cost_business_domain', 'danger', 'N', '业务域：材料成本' FROM dual
  UNION ALL SELECT 6, '制造成本', 'MANUFACTURE', 'cost_business_domain', 'default', 'N', '业务域：制造成本' FROM dual
  UNION ALL SELECT 1, '正常', '0', 'cost_scene_status', 'success', 'Y', '场景可维护且可被下游使用' FROM dual
  UNION ALL SELECT 2, '停用', '1', 'cost_scene_status', 'danger', 'N', '场景已停用' FROM dual
  UNION ALL SELECT 3, '草稿', '2', 'cost_scene_status', 'warning', 'N', '场景仍在整理中' FROM dual
  UNION ALL SELECT 1, '合同场景', 'CONTRACT', 'cost_scene_type', 'primary', 'Y', '以合同为边界维护核算配置' FROM dual
  UNION ALL SELECT 2, '核算主题', 'THEME', 'cost_scene_type', 'success', 'N', '以统一核算主题组织配置' FROM dual
  UNION ALL SELECT 3, '业务方案', 'PLAN', 'cost_scene_type', 'warning', 'N', '以具体业务方案组织配置' FROM dual
  UNION ALL SELECT 4, '公司级核算域', 'COMPANY', 'cost_scene_type', 'info', 'N', '以公司级统一口径组织配置' FROM dual
  UNION ALL SELECT 1, '正常', '0', 'cost_fee_status', 'success', 'Y', '费目可维护' FROM dual
  UNION ALL SELECT 2, '停用', '1', 'cost_fee_status', 'danger', 'N', '费目停用' FROM dual
  UNION ALL SELECT 1, '吨', '吨', 'cost_unit_code', 'primary', 'Y', '重量单位' FROM dual
  UNION ALL SELECT 2, '天', '天', 'cost_unit_code', 'success', 'N', '时间单位' FROM dual
  UNION ALL SELECT 3, '次', '次', 'cost_unit_code', 'info', 'N', '次数单位' FROM dual
  UNION ALL SELECT 4, '航次', '航次', 'cost_unit_code', 'warning', 'N', '航运业务单位' FROM dual
  UNION ALL SELECT 5, '人', '人', 'cost_unit_code', 'primary', 'N', '人员单位' FROM dual
  UNION ALL SELECT 6, '箱', '箱', 'cost_unit_code', 'success', 'N', '箱量单位' FROM dual
  UNION ALL SELECT 7, '元', '元', 'cost_unit_code', 'danger', 'N', '金额单位' FROM dual
  UNION ALL SELECT 8, '平方米*天', '平方米*天', 'cost_unit_code', 'warning', 'N', '仓储复合单位' FROM dual
  UNION ALL SELECT 1, '正常', '0', 'cost_variable_group_status', 'success', 'Y', '要素分组可维护' FROM dual
  UNION ALL SELECT 2, '停用', '1', 'cost_variable_group_status', 'danger', 'N', '要素分组停用' FROM dual
  UNION ALL SELECT 1, '文本', 'TEXT', 'cost_variable_type', 'primary', 'Y', '文本要素' FROM dual
  UNION ALL SELECT 2, '数值', 'NUMBER', 'cost_variable_type', 'success', 'N', '数值要素' FROM dual
  UNION ALL SELECT 3, '字典下拉', 'DICT', 'cost_variable_type', 'warning', 'N', '字典要素' FROM dual
  UNION ALL SELECT 4, '接口下拉', 'REMOTE', 'cost_variable_type', 'info', 'N', '第三方接口要素' FROM dual
  UNION ALL SELECT 5, '公式', 'FORMULA', 'cost_variable_type', 'danger', 'N', '公式要素' FROM dual
  UNION ALL SELECT 6, '布尔', 'BOOLEAN', 'cost_variable_type', 'default', 'N', '布尔要素' FROM dual
  UNION ALL SELECT 7, '日期', 'DATE', 'cost_variable_type', 'default', 'N', '日期要素' FROM dual
  UNION ALL SELECT 1, '手工输入', 'INPUT', 'cost_variable_source_type', 'primary', 'Y', '由调用方传入' FROM dual
  UNION ALL SELECT 2, '字典接入', 'DICT', 'cost_variable_source_type', 'success', 'N', '从字典读取' FROM dual
  UNION ALL SELECT 3, '第三方接口', 'REMOTE', 'cost_variable_source_type', 'warning', 'N', '从远程接口读取' FROM dual
  UNION ALL SELECT 4, '公式派生', 'FORMULA', 'cost_variable_source_type', 'info', 'N', '由公式派生' FROM dual
  UNION ALL SELECT 1, '字符串', 'STRING', 'cost_variable_data_type', 'primary', 'Y', '字符串数据' FROM dual
  UNION ALL SELECT 2, '数值', 'NUMBER', 'cost_variable_data_type', 'success', 'N', '数值数据' FROM dual
  UNION ALL SELECT 3, '布尔', 'BOOLEAN', 'cost_variable_data_type', 'warning', 'N', '布尔数据' FROM dual
  UNION ALL SELECT 4, '日期', 'DATE', 'cost_variable_data_type', 'info', 'N', '日期数据' FROM dual
  UNION ALL SELECT 5, 'JSON', 'JSON', 'cost_variable_data_type', 'default', 'N', 'JSON 数据' FROM dual
  UNION ALL SELECT 1, '无鉴权', 'NONE', 'cost_variable_auth_type', 'info', 'Y', '无需鉴权' FROM dual
  UNION ALL SELECT 2, 'Basic', 'BASIC', 'cost_variable_auth_type', 'primary', 'N', 'Basic 鉴权' FROM dual
  UNION ALL SELECT 3, 'Bearer Token', 'BEARER', 'cost_variable_auth_type', 'success', 'N', 'Bearer Token 鉴权' FROM dual
  UNION ALL SELECT 4, 'API Key', 'API_KEY', 'cost_variable_auth_type', 'warning', 'N', 'API Key 鉴权' FROM dual
  UNION ALL SELECT 1, '实时拉取', 'REALTIME', 'cost_variable_sync_mode', 'primary', 'Y', '调用时实时拉取' FROM dual
  UNION ALL SELECT 2, '准实时缓存', 'NEAR_REALTIME', 'cost_variable_sync_mode', 'success', 'N', '按短周期缓存刷新' FROM dual
  UNION ALL SELECT 3, '定时同步', 'SCHEDULED', 'cost_variable_sync_mode', 'warning', 'N', '按任务定时同步' FROM dual
  UNION ALL SELECT 1, '不缓存', 'NONE', 'cost_variable_cache_policy', 'info', 'Y', '不做缓存' FROM dual
  UNION ALL SELECT 2, 'TTL缓存', 'TTL', 'cost_variable_cache_policy', 'success', 'N', '按失效时间缓存' FROM dual
  UNION ALL SELECT 3, '手动刷新', 'MANUAL_REFRESH', 'cost_variable_cache_policy', 'primary', 'N', '仅手动刷新' FROM dual
  UNION ALL SELECT 1, '失败即终止', 'FAIL_FAST', 'cost_variable_fallback_policy', 'danger', 'Y', '失败后直接终止' FROM dual
  UNION ALL SELECT 2, '回退默认值', 'DEFAULT_VALUE', 'cost_variable_fallback_policy', 'warning', 'N', '失败后使用默认值' FROM dual
  UNION ALL SELECT 3, '回退快照值', 'LAST_SNAPSHOT', 'cost_variable_fallback_policy', 'info', 'N', '失败后回退最近快照值' FROM dual
  UNION ALL SELECT 1, '正常', '0', 'cost_variable_status', 'success', 'Y', '要素可维护' FROM dual
  UNION ALL SELECT 2, '停用', '1', 'cost_variable_status', 'danger', 'N', '要素停用' FROM dual
  UNION ALL SELECT 1, '正常', '0', 'cost_formula_status', 'success', 'Y', '公式可用' FROM dual
  UNION ALL SELECT 2, '停用', '1', 'cost_formula_status', 'info', 'N', '公式停用' FROM dual
  UNION ALL SELECT 1, '数值', 'NUMBER', 'cost_formula_return_type', 'primary', 'Y', '公式返回数值' FROM dual
  UNION ALL SELECT 2, '布尔', 'BOOLEAN', 'cost_formula_return_type', 'warning', 'N', '公式返回布尔值' FROM dual
  UNION ALL SELECT 3, '文本', 'STRING', 'cost_formula_return_type', 'info', 'N', '公式返回文本' FROM dual
  UNION ALL SELECT 4, 'JSON', 'JSON', 'cost_formula_return_type', 'danger', 'N', '公式返回结构化对象' FROM dual
  UNION ALL SELECT 1, '正常', '0', 'cost_rule_status', 'success', 'Y', '规则可维护' FROM dual
  UNION ALL SELECT 2, '停用', '1', 'cost_rule_status', 'danger', 'N', '规则停用' FROM dual
  UNION ALL SELECT 1, '固定费率', 'FIXED_RATE', 'cost_rule_type', 'primary', 'Y', '固定费率规则' FROM dual
  UNION ALL SELECT 2, '固定金额', 'FIXED_AMOUNT', 'cost_rule_type', 'success', 'N', '固定金额规则' FROM dual
  UNION ALL SELECT 3, '公式金额', 'FORMULA', 'cost_rule_type', 'warning', 'N', '公式金额规则' FROM dual
  UNION ALL SELECT 4, '阶梯费率', 'TIER_RATE', 'cost_rule_type', 'info', 'N', '阶梯费率规则' FROM dual
  UNION ALL SELECT 1, '且', 'AND', 'cost_rule_condition_logic', 'primary', 'Y', '条件同时满足' FROM dual
  UNION ALL SELECT 2, '或', 'OR', 'cost_rule_condition_logic', 'warning', 'N', '条件任一满足' FROM dual
  UNION ALL SELECT 1, '等于', 'EQ', 'cost_rule_operator', 'primary', 'Y', '等于' FROM dual
  UNION ALL SELECT 2, '不等于', 'NE', 'cost_rule_operator', 'info', 'N', '不等于' FROM dual
  UNION ALL SELECT 3, '大于', 'GT', 'cost_rule_operator', 'warning', 'N', '大于' FROM dual
  UNION ALL SELECT 4, '大于等于', 'GE', 'cost_rule_operator', 'success', 'N', '大于等于' FROM dual
  UNION ALL SELECT 5, '小于', 'LT', 'cost_rule_operator', 'warning', 'N', '小于' FROM dual
  UNION ALL SELECT 6, '小于等于', 'LE', 'cost_rule_operator', 'success', 'N', '小于等于' FROM dual
  UNION ALL SELECT 7, '包含任一值', 'IN', 'cost_rule_operator', 'info', 'N', '多值包含' FROM dual
  UNION ALL SELECT 8, '不包含', 'NOT_IN', 'cost_rule_operator', 'danger', 'N', '多值排除' FROM dual
  UNION ALL SELECT 9, '区间', 'BETWEEN', 'cost_rule_operator', 'primary', 'N', '区间比较' FROM dual
  UNION ALL SELECT 10, '表达式', 'EXPR', 'cost_rule_operator', 'default', 'N', '表达式条件' FROM dual
  UNION ALL SELECT 11, '为空', 'IS_NULL', 'cost_rule_operator', 'warning', 'N', '空值判断' FROM dual
  UNION ALL SELECT 12, '不为空', 'IS_NOT_NULL', 'cost_rule_operator', 'success', 'N', '非空判断' FROM dual
  UNION ALL SELECT 1, '左闭右开 [a,b)', 'LEFT_CLOSED_RIGHT_OPEN', 'cost_rule_interval_mode', 'primary', 'Y', 'start <= x < end' FROM dual
  UNION ALL SELECT 2, '左开右闭 (a,b]', 'LEFT_OPEN_RIGHT_CLOSED', 'cost_rule_interval_mode', 'warning', 'N', 'start < x <= end' FROM dual
  UNION ALL SELECT 1, '已发布', 'PUBLISHED', 'cost_publish_version_status', 'primary', 'Y', '已发布未生效' FROM dual
  UNION ALL SELECT 2, '生效中', 'ACTIVE', 'cost_publish_version_status', 'success', 'N', '当前生效版本' FROM dual
  UNION ALL SELECT 3, '已回滚', 'ROLLED_BACK', 'cost_publish_version_status', 'warning', 'N', '已被回滚的版本' FROM dual
  UNION ALL SELECT 1, '成功', 'SUCCESS', 'cost_simulation_status', 'success', 'Y', '试算成功' FROM dual
  UNION ALL SELECT 2, '失败', 'FAILED', 'cost_simulation_status', 'danger', 'N', '试算失败' FROM dual
  UNION ALL SELECT 1, '单笔正式核算', 'FORMAL_SINGLE', 'cost_calc_task_type', 'primary', 'Y', '单笔正式核算' FROM dual
  UNION ALL SELECT 2, '批量正式核算', 'FORMAL_BATCH', 'cost_calc_task_type', 'warning', 'N', '批量正式核算' FROM dual
  UNION ALL SELECT 1, '待执行', 'INIT', 'cost_calc_task_status', 'info', 'Y', '任务初始化' FROM dual
  UNION ALL SELECT 2, '执行中', 'RUNNING', 'cost_calc_task_status', 'primary', 'N', '任务执行中' FROM dual
  UNION ALL SELECT 3, '成功', 'SUCCESS', 'cost_calc_task_status', 'success', 'N', '任务全部成功' FROM dual
  UNION ALL SELECT 4, '部分成功', 'PART_SUCCESS', 'cost_calc_task_status', 'warning', 'N', '任务部分成功' FROM dual
  UNION ALL SELECT 5, '失败', 'FAILED', 'cost_calc_task_status', 'danger', 'N', '任务失败' FROM dual
  UNION ALL SELECT 6, '已取消', 'CANCELLED', 'cost_calc_task_status', 'default', 'N', '任务已取消' FROM dual
  UNION ALL SELECT 1, '成功', 'SUCCESS', 'cost_result_status', 'success', 'Y', '结果成功' FROM dual
  UNION ALL SELECT 2, '失败', 'FAILED', 'cost_result_status', 'danger', 'N', '结果失败' FROM dual
  UNION ALL SELECT 3, '调整后', 'ADJUSTED', 'cost_result_status', 'warning', 'N', '结果经调整' FROM dual
) seed
ON (target.dict_type = seed.dict_type AND target.dict_value = seed.dict_value)
WHEN NOT MATCHED THEN INSERT
  (dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, remark)
VALUES
  (seed.dict_sort, seed.dict_label, seed.dict_value, seed.dict_type, NULL, seed.list_class,
   seed.is_default, '0', 'cost-lite', SYSTIMESTAMP, seed.remark);

-- End of Cost Lite Oracle schema baseline.
