-- Cost Lite Oracle optional formal/open schema
-- Source: the same frozen mother cost_init.sql entity contract; execute after cost-lite-schema.sql.
-- This script is required only when formal tasks/results, recalculation, alarms or open-app APIs are enabled.
-- Oracle 12c+ / 19c / 23ai.

-- cost_bill_period
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_bill_period (
  period_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id NUMBER(19) not null,
  bill_month VARCHAR2(7 CHAR) not null,
  period_status VARCHAR2(32 CHAR) DEFAULT 'NOT_STARTED' NOT NULL,
  active_version_id NUMBER(19) default null,
  result_count NUMBER(19) DEFAULT 0 NOT NULL,
  amount_total NUMBER(18,2) DEFAULT 0.00 NOT NULL,
  last_task_id NUMBER(19) default null,
  last_task_no VARCHAR2(64 CHAR) DEFAULT NULL,
  sealed_by VARCHAR2(64 CHAR) DEFAULT NULL,
  sealed_time TIMESTAMP(6) default null,
  create_by VARCHAR2(64 CHAR) DEFAULT NULL,
  create_time TIMESTAMP(6) default SYSTIMESTAMP,
  update_by VARCHAR2(64 CHAR) DEFAULT NULL,
  update_time TIMESTAMP(6) default SYSTIMESTAMP,
  remark VARCHAR2(500 CHAR) DEFAULT NULL,
  constraint uk_cost_bill_period_scene_month unique (scene_id, bill_month),
  constraint pk_cost_bill_period primary key (period_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_recalc_order
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_recalc_order (
  recalc_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id NUMBER(19) not null,
  bill_month VARCHAR2(7 CHAR) not null,
  version_id NUMBER(19) not null,
  period_id NUMBER(19) default null,
  baseline_task_id NUMBER(19) default null,
  baseline_task_no VARCHAR2(64 CHAR) DEFAULT NULL,
  target_task_id NUMBER(19) default null,
  target_task_no VARCHAR2(64 CHAR) DEFAULT NULL,
  recalc_status VARCHAR2(32 CHAR) DEFAULT 'PENDING_APPROVAL' NOT NULL,
  apply_reason VARCHAR2(500 CHAR) DEFAULT NULL,
  approve_opinion VARCHAR2(500 CHAR) DEFAULT NULL,
  diff_summary_json CLOB default null,
  diff_amount NUMBER(18,2) DEFAULT 0.00 NOT NULL,
  request_no VARCHAR2(64 CHAR) DEFAULT NULL,
  approve_by VARCHAR2(64 CHAR) DEFAULT NULL,
  approve_time TIMESTAMP(6) default null,
  execute_by VARCHAR2(64 CHAR) DEFAULT NULL,
  execute_time TIMESTAMP(6) default null,
  finish_time TIMESTAMP(6) default null,
  create_by VARCHAR2(64 CHAR) DEFAULT NULL,
  create_time TIMESTAMP(6) default SYSTIMESTAMP,
  update_by VARCHAR2(64 CHAR) DEFAULT NULL,
  update_time TIMESTAMP(6) default SYSTIMESTAMP,
  remark VARCHAR2(500 CHAR) DEFAULT NULL,
  constraint pk_cost_recalc_order primary key (recalc_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_alarm_record
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_alarm_record (
  alarm_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id NUMBER(19) default null,
  version_id NUMBER(19) default null,
  task_id NUMBER(19) default null,
  detail_id NUMBER(19) default null,
  bill_month VARCHAR2(7 CHAR) DEFAULT NULL,
  alarm_type VARCHAR2(32 CHAR) not null,
  alarm_level VARCHAR2(32 CHAR) DEFAULT 'WARN' NOT NULL,
  alarm_status VARCHAR2(32 CHAR) DEFAULT 'OPEN' NOT NULL,
  source_key VARCHAR2(128 CHAR) DEFAULT NULL,
  alarm_title VARCHAR2(200 CHAR) DEFAULT NULL,
  alarm_content VARCHAR2(1000 CHAR) DEFAULT NULL,
  trigger_time TIMESTAMP(6) default SYSTIMESTAMP,
  first_trigger_time TIMESTAMP(6) null,
  latest_trigger_time TIMESTAMP(6) null,
  occurrence_count NUMBER(10) DEFAULT 1 NOT NULL,
  ack_by VARCHAR2(64 CHAR) DEFAULT NULL,
  ack_time TIMESTAMP(6) default null,
  resolve_by VARCHAR2(64 CHAR) DEFAULT NULL,
  resolve_time TIMESTAMP(6) default null,
  create_by VARCHAR2(64 CHAR) DEFAULT NULL,
  create_time TIMESTAMP(6) default SYSTIMESTAMP,
  update_by VARCHAR2(64 CHAR) DEFAULT NULL,
  update_time TIMESTAMP(6) default SYSTIMESTAMP,
  remark VARCHAR2(500 CHAR) DEFAULT NULL,
  constraint pk_cost_alarm_record primary key (alarm_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_access_profile
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_access_profile (
    profile_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    scene_id NUMBER(19) not null,
    fee_id NUMBER(19) null,
    fee_scope_type VARCHAR2(16 CHAR) DEFAULT 'ALL' NOT NULL,
    fee_ids_json CLOB null,
    version_id NUMBER(19) null,
    profile_code VARCHAR2(64 CHAR) not null,
    profile_name VARCHAR2(128 CHAR) not null,
    source_type VARCHAR2(32 CHAR) DEFAULT 'RAW_JSON' NOT NULL,
    task_type VARCHAR2(32 CHAR) DEFAULT 'FORMAL_BATCH' NOT NULL,
    request_method VARCHAR2(16 CHAR) DEFAULT 'GET' NOT NULL,
    endpoint_url VARCHAR2(255 CHAR) null,
    auth_type VARCHAR2(32 CHAR) DEFAULT 'NONE' NOT NULL,
    auth_config_json CLOB null,
    fetch_config_json CLOB null,
    mapping_json CLOB null,
    sample_payload_json CLOB null,
    sample_input_json CLOB null,
    status CHAR(1 CHAR) DEFAULT '0' NOT NULL,
    sort_no NUMBER(10) DEFAULT 0,
    create_by VARCHAR2(64 CHAR) null,
    create_time TIMESTAMP(6) null,
    update_by VARCHAR2(64 CHAR) null,
    update_time TIMESTAMP(6) null,
    remark VARCHAR2(500 CHAR) null,
  constraint uk_cost_access_profile_scene_code unique (scene_id, profile_code),
  constraint pk_cost_access_profile primary key (profile_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_calc_input_batch
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_calc_input_batch (
  batch_id                   NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  batch_no                   VARCHAR2(64 CHAR)     not null,
  scene_id                   NUMBER(19)          not null,
  version_id                 NUMBER(19)          default null,
  bill_month                 VARCHAR2(16 CHAR)     DEFAULT NULL NOT NULL,
  source_type                VARCHAR2(32 CHAR)     DEFAULT 'JSON_IMPORT' NOT NULL,
  batch_status               VARCHAR2(32 CHAR)     DEFAULT 'READY' NOT NULL,
  total_count                NUMBER(10)             DEFAULT 0 NOT NULL,
  valid_count                NUMBER(10)             DEFAULT 0 NOT NULL,
  error_count                NUMBER(10)             DEFAULT 0 NOT NULL,
  remark                     VARCHAR2(500 CHAR)    default null,
  error_message              VARCHAR2(1000 CHAR)   DEFAULT NULL,
  access_profile_id          NUMBER(19)          null,
  checkpoint_json            CLOB        null,
  create_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  update_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  update_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_calc_input_batch_no unique (batch_no),
  constraint fk_cost_calc_input_batch_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint fk_cost_calc_input_batch_version foreign key (version_id) references cost_publish_version (version_id),
  constraint pk_cost_calc_input_batch primary key (batch_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_calc_input_batch_item
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_calc_input_batch_item (
  item_id                    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  batch_id                   NUMBER(19)          not null,
  batch_no                   VARCHAR2(64 CHAR)     not null,
  item_no                    NUMBER(10)             not null,
  biz_no                     VARCHAR2(128 CHAR)    not null,
  item_status                VARCHAR2(32 CHAR)     DEFAULT 'READY' NOT NULL,
  input_json                 CLOB            not null,
  error_message              VARCHAR2(1000 CHAR)   DEFAULT NULL,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  update_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_calc_input_batch_item unique (batch_id, biz_no),
  constraint fk_cost_calc_input_batch_item_batch foreign key (batch_id) references cost_calc_input_batch (batch_id),
  constraint pk_cost_calc_input_batch_item primary key (item_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_calc_task
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_calc_task (
  task_id                    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  task_no                    VARCHAR2(64 CHAR)     not null,
  scene_id                   NUMBER(19)          not null,
  version_id                 NUMBER(19)          not null,
  task_type                  VARCHAR2(32 CHAR)     not null,
  bill_month                 VARCHAR2(16 CHAR)     DEFAULT NULL,
  source_count               NUMBER(10)             DEFAULT 0 NOT NULL,
  success_count              NUMBER(10)             DEFAULT 0 NOT NULL,
  fail_count                 NUMBER(10)             DEFAULT 0 NOT NULL,
  task_status                VARCHAR2(32 CHAR)     DEFAULT 'INIT' NOT NULL,
  progress_percent           NUMBER(5,2)    DEFAULT 0 NOT NULL,
  started_time               TIMESTAMP(6)        default null,
  finished_time              TIMESTAMP(6)        default null,
  duration_ms                NUMBER(19)          default 0,
  request_no                 VARCHAR2(64 CHAR)     DEFAULT NULL,
  request_no_key             GENERATED ALWAYS AS (CAST(request_no AS VARCHAR2(64 CHAR))) VIRTUAL,
  execute_node               VARCHAR2(128 CHAR)    DEFAULT NULL,
  input_source_type          VARCHAR2(32 CHAR)     DEFAULT 'INLINE_JSON' NOT NULL,
  source_batch_no            VARCHAR2(64 CHAR)     DEFAULT NULL,
  error_message              VARCHAR2(1000 CHAR)   DEFAULT NULL,
  remark                     VARCHAR2(500 CHAR)    default null,
  create_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  update_by                  VARCHAR2(64 CHAR)     DEFAULT NULL,
  update_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_calc_task_no unique (task_no),
  constraint uk_cost_calc_task_request_no unique (scene_id, version_id, bill_month, request_no_key),
  constraint fk_cost_calc_task_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint fk_cost_calc_task_version foreign key (version_id) references cost_publish_version (version_id),
  constraint pk_cost_calc_task primary key (task_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_calc_task_detail
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_calc_task_detail (
  detail_id                  NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  task_id                    NUMBER(19)          not null,
  task_no                    VARCHAR2(64 CHAR)     not null,
  biz_no                     VARCHAR2(128 CHAR)    not null,
  partition_no               NUMBER(10)             DEFAULT 1 NOT NULL,
  detail_status              VARCHAR2(32 CHAR)     DEFAULT 'INIT' NOT NULL,
  retry_count                NUMBER(10)             DEFAULT 0 NOT NULL,
  input_json                 CLOB            not null,
  result_summary             VARCHAR2(1000 CHAR)   DEFAULT NULL,
  error_message              VARCHAR2(1000 CHAR)   DEFAULT NULL,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  update_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_calc_task_detail unique (task_id, biz_no),
  constraint fk_cost_calc_task_detail_task foreign key (task_id) references cost_calc_task (task_id),
  constraint pk_cost_calc_task_detail primary key (detail_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_calc_task_partition
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_calc_task_partition (
  partition_id               NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  task_id                    NUMBER(19)          not null,
  task_no                    VARCHAR2(64 CHAR)     not null,
  partition_no               NUMBER(10)             not null,
  start_item_no              NUMBER(10)             DEFAULT 1 NOT NULL,
  end_item_no                NUMBER(10)             DEFAULT 1 NOT NULL,
  partition_status           VARCHAR2(32 CHAR)     DEFAULT 'INIT' NOT NULL,
  total_count                NUMBER(10)             DEFAULT 0 NOT NULL,
  processed_count            NUMBER(10)             DEFAULT 0 NOT NULL,
  success_count              NUMBER(10)             DEFAULT 0 NOT NULL,
  fail_count                 NUMBER(10)             DEFAULT 0 NOT NULL,
  amount_total               NUMBER(18,2)   DEFAULT 0.00 NOT NULL,
  persist_mode               VARCHAR2(32 CHAR)     DEFAULT 'BATCH' NOT NULL,
  recovery_hint              VARCHAR2(500 CHAR)    DEFAULT NULL NOT NULL,
  last_error_stage           VARCHAR2(64 CHAR)     DEFAULT NULL NOT NULL,
  execute_node               VARCHAR2(64 CHAR)     default null,
  claim_time                 TIMESTAMP(6)        default null,
  started_time               TIMESTAMP(6)        default null,
  finished_time              TIMESTAMP(6)        default null,
  duration_ms                NUMBER(19)          default 0,
  last_error                 VARCHAR2(1000 CHAR)   DEFAULT NULL,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  update_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint uk_cost_calc_task_partition unique (task_id, partition_no),
  constraint fk_cost_calc_task_partition_task foreign key (task_id) references cost_calc_task (task_id),
  constraint pk_cost_calc_task_partition primary key (partition_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_result_ledger
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_result_ledger (
  result_id                  NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  task_id                    NUMBER(19)          not null,
  task_no                    VARCHAR2(64 CHAR)     not null,
  scene_id                   NUMBER(19)          not null,
  version_id                 NUMBER(19)          not null,
  fee_id                     NUMBER(19)          not null,
  fee_code                   VARCHAR2(64 CHAR)     not null,
  fee_name                   VARCHAR2(128 CHAR)    not null,
  biz_no                     VARCHAR2(128 CHAR)    not null,
  bill_month                 VARCHAR2(16 CHAR)     not null,
  object_dimension           VARCHAR2(64 CHAR)     DEFAULT NULL,
  object_code                VARCHAR2(128 CHAR)    DEFAULT NULL,
  object_name                VARCHAR2(128 CHAR)    DEFAULT NULL,
  quantity_value             NUMBER(18,4)   default null,
  unit_price                 NUMBER(18,6)   default null,
  amount_value               NUMBER(18,2)   not null,
  currency_code              VARCHAR2(32 CHAR)     default 'CNY',
  result_status              VARCHAR2(32 CHAR)     DEFAULT 'SUCCESS' NOT NULL,
  trace_id                   NUMBER(19)          default null,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint fk_cost_result_task foreign key (task_id) references cost_calc_task (task_id),
  constraint fk_cost_result_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint fk_cost_result_version foreign key (version_id) references cost_publish_version (version_id),
  constraint fk_cost_result_fee foreign key (fee_id) references cost_fee_item (fee_id),
  constraint pk_cost_result_ledger primary key (result_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_result_trace
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_result_trace (
  trace_id                   NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  scene_id                   NUMBER(19)          not null,
  version_id                 NUMBER(19)          not null,
  rule_id                    NUMBER(19)          default null,
  tier_id                    NUMBER(19)          default null,
  variable_json              CLOB            default null,
  condition_json             CLOB            default null,
  pricing_json               CLOB            default null,
  timeline_json              CLOB            default null,
  create_time                TIMESTAMP(6)        default SYSTIMESTAMP,
  constraint fk_cost_trace_scene foreign key (scene_id) references cost_scene (scene_id),
  constraint fk_cost_trace_version foreign key (version_id) references cost_publish_version (version_id),
  constraint fk_cost_trace_rule foreign key (rule_id) references cost_rule (rule_id),
  constraint fk_cost_trace_tier foreign key (tier_id) references cost_rule_tier (tier_id),
  constraint pk_cost_result_trace primary key (trace_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================
-- cost_open_app
-- =========================================================
BEGIN
  EXECUTE IMMEDIATE q'~
CREATE TABLE cost_open_app (
    app_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    app_code VARCHAR2(64 CHAR) not null,
    app_name VARCHAR2(128 CHAR) not null,
    app_secret_hash CHAR(64 CHAR) not null,
    scene_scope_type VARCHAR2(16 CHAR) DEFAULT 'ALL' NOT NULL,
    scene_ids_json CLOB null,
    allow_draft_snapshot NUMBER(1) DEFAULT 0 NOT NULL,
    token_ttl_seconds NUMBER(10) DEFAULT 7200 NOT NULL,
    effective_start_time TIMESTAMP(6) null,
    effective_end_time TIMESTAMP(6) null,
    status CHAR(1 CHAR) DEFAULT '0' NOT NULL,
    sort_no NUMBER(10) DEFAULT 0,
    create_by VARCHAR2(64 CHAR) null,
    create_time TIMESTAMP(6) null,
    update_by VARCHAR2(64 CHAR) null,
    update_time TIMESTAMP(6) null,
    remark VARCHAR2(500 CHAR) null,
  constraint uk_cost_open_app_code unique (app_code),
  constraint pk_cost_open_app primary key (app_id)
)
~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- =========================================================

-- =========================================================
-- Secondary indexes for optional formal/open tables
-- =========================================================

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_bill_period_status ON cost_bill_period (period_status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_bill_period_version ON cost_bill_period (active_version_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_recalc_scene_month ON cost_recalc_order (scene_id, bill_month)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_recalc_status ON cost_recalc_order (recalc_status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_recalc_target_task ON cost_recalc_order (target_task_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_alarm_scene_time ON cost_alarm_record (scene_id, trigger_time)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_alarm_task ON cost_alarm_record (task_id, detail_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_alarm_status ON cost_alarm_record (alarm_status, alarm_level)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_alarm_source_status ON cost_alarm_record (source_key, alarm_status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_access_profile_fee ON cost_access_profile (fee_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_access_profile_status ON cost_access_profile (status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_input_batch_scene_month ON cost_calc_input_batch (scene_id, bill_month)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_input_batch_item_batch ON cost_calc_input_batch_item (batch_id, item_no)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_task_scene_month ON cost_calc_task (scene_id, bill_month)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_task_scene_status ON cost_calc_task (scene_id, task_status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_task_version ON cost_calc_task (version_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_task_detail_task_status ON cost_calc_task_detail (task_id, detail_status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_task_detail_task_partition ON cost_calc_task_detail (task_id, partition_no)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_task_detail_task_no ON cost_calc_task_detail (task_no)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_task_partition_task_status ON cost_calc_task_partition (task_id, partition_status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_task_partition_task_no ON cost_calc_task_partition (task_no)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_calc_task_partition_status_claim ON cost_calc_task_partition (partition_status, claim_time)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_result_scene_month ON cost_result_ledger (scene_id, bill_month)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_result_task_fee ON cost_result_ledger (task_id, fee_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_result_biz_fee ON cost_result_ledger (biz_no, fee_code)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_result_version ON cost_result_ledger (version_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_trace_scene_ver ON cost_result_trace (scene_id, version_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_trace_rule ON cost_result_trace (rule_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_trace_tier ON cost_result_trace (tier_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cost_open_app_status ON cost_open_app (status)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- Formal/open dictionary seeds; the dictionary tables themselves are created by cost-lite-schema.sql.
MERGE INTO sys_dict_type target
USING (
  SELECT '核算-正式任务类型' dict_name, 'cost_calc_task_type' dict_type, '正式任务类型' remark FROM dual
  UNION ALL SELECT '核算-正式任务状态', 'cost_calc_task_status', '正式任务状态' FROM dual
  UNION ALL SELECT '核算-结果状态', 'cost_result_status', '正式结果状态' FROM dual
) seed
ON (target.dict_type = seed.dict_type)
WHEN NOT MATCHED THEN INSERT (dict_name, dict_type, status, create_by, create_time, remark)
VALUES (seed.dict_name, seed.dict_type, '0', 'cost-lite', SYSTIMESTAMP, seed.remark);

MERGE INTO sys_dict_data target
USING (
  SELECT 1 dict_sort, '单笔正式核算' dict_label, 'FORMAL_SINGLE' dict_value, 'cost_calc_task_type' dict_type, 'primary' list_class, 'Y' is_default, '单笔正式核算' remark FROM dual
  UNION ALL SELECT 2, '批量正式核算', 'FORMAL_BATCH', 'cost_calc_task_type', 'warning', 'N', '批量正式核算' FROM dual
  UNION ALL SELECT 1, '待执行', 'INIT', 'cost_calc_task_status', 'info', 'Y', '任务初始化' FROM dual
  UNION ALL SELECT 2, '执行中', 'RUNNING', 'cost_calc_task_status', 'primary', 'N', '任务执行中' FROM dual
  UNION ALL SELECT 3, '成功', 'SUCCESS', 'cost_calc_task_status', 'success', 'N', '任务全部成功' FROM dual
  UNION ALL SELECT 4, '部分成功', 'PART_SUCCESS', 'cost_calc_task_status', 'warning', 'N', '任务部分成功' FROM dual
  UNION ALL SELECT 5, '失败', 'FAILED', 'cost_calc_task_status', 'danger', 'N', '任务失败' FROM dual
  UNION ALL SELECT 6, '已取消', 'CANCELLED', 'cost_calc_task_status', 'default', 'N', '任务已取消' FROM dual
  UNION ALL SELECT 1, '成功', 'SUCCESS', 'cost_result_status', 'success', 'Y', '结果成功' FROM dual
  UNION ALL SELECT 2, '失败', 'FAILED', 'cost_result_status', 'danger', 'N', '结果失败' FROM dual
  UNION ALL SELECT 3, '调整后', 'ADJUSTED', 'cost_result_status', 'warning', 'N', '结果经调整' FROM dual
) seed
ON (target.dict_type = seed.dict_type AND target.dict_value = seed.dict_value)
WHEN NOT MATCHED THEN INSERT (dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, remark)
VALUES (seed.dict_sort, seed.dict_label, seed.dict_value, seed.dict_type, NULL, seed.list_class, seed.is_default, '0', 'cost-lite', SYSTIMESTAMP, seed.remark);

-- End of Cost Lite Oracle optional formal/open schema.
